/**
 * Integration tests for the full transpile pipeline.
 *
 * These tests exercise the end-to-end flow:
 *   .test.yaml → parseYamlTestFile → transpileYamlTest → .yaml.spec.ts
 *
 * Each test creates a temp directory with YAML files, runs transpileAllYamlTests(),
 * and verifies the generated .yaml.spec.ts output.
 */

import { test, expect } from '@playwright/test';
import { mkdirSync, writeFileSync, readFileSync, existsSync, utimesSync, statSync } from 'fs';
import * as fs from 'fs';
import { join } from 'path';
import { tmpdir } from 'os';
import { transpileAllYamlTests } from '../../src/transpile';

function createTempDir(): string {
  const dir = join(tmpdir(), `shiplight-integration-${Date.now()}-${Math.random().toString(36).slice(2)}`);
  mkdirSync(dir, { recursive: true });
  return dir;
}

async function withTempDir(fn: (dir: string) => void | Promise<void>): Promise<void> {
  const dir = createTempDir();
  try {
    await fn(dir);
  } finally {
    fs.rmSync(dir, { recursive: true });
  }
}

test.describe('transpile pipeline', () => {
  test('transpiles a basic YAML test file', async () => {
    await withTempDir((dir) => {
      writeFileSync(join(dir, 'login.test.yaml'), `
goal: Verify login works
statements:
  - URL: https://example.com/login
  - intent: Navigate to the login page
  - intent: Enter username and password
  - intent: Click the login button
  - VERIFY: Dashboard is visible
`);

      transpileAllYamlTests({ cwd: dir });

      const outPath = join(dir, 'login.yaml.spec.ts');
      expect(existsSync(outPath)).toBe(true);

      const code = readFileSync(outPath, 'utf-8');

      // Version header
      expect(code).toMatch(/^\/\/ @generated by shiplightai v(\d+\.\d+\.\d+|dev)\+fmt\d+/);

      // Imports
      expect(code).toContain("import { test, expect } from 'shiplightai/fixture'");

      // Test name from goal
      expect(code).toContain("test('Verify login works'");

      // Test fixture
      expect(code).toContain('async ({ page, agent })');

      // URL navigation
      expect(code).toContain('/login');

      // Draft statements → agent.run
      expect(code).toContain('agent.run(page');
      expect(code).toContain('Navigate to the login page');
      expect(code).toContain('Enter username and password');
      expect(code).toContain('Click the login button');

      // VERIFY → agent.assert
      expect(code).toContain('agent.assert(page');
      expect(code).toContain('Dashboard is visible');
    });
  });

  test('transpiles YAML with action entities', async () => {
    await withTempDir((dir) => {
      writeFileSync(join(dir, 'actions.test.yaml'), `
goal: Action entity test
statements:
  - URL: https://example.com
  - action: click
    description: Click Submit
    locator: "getByRole('button', { name: 'Submit' })"
  - action: input_text
    description: Type email
    locator: "getByLabel('Email')"
    text: "user@test.com"
  - action: press
    description: Press Enter
    keys: Enter
`);

      transpileAllYamlTests({ cwd: dir });

      const code = readFileSync(join(dir, 'actions.yaml.spec.ts'), 'utf-8');

      // Click with locator → agent.step
      expect(code).toContain('agent.step(page');
      expect(code).toContain("getByRole('button', { name: 'Submit' })");

      // input_text → execAction
      expect(code).toContain('agent.execAction("input_text"');
      expect(code).toContain('"user@test.com"');

      // press → page.keyboard.press
      expect(code).toContain('page.keyboard.press("Enter")');
    });
  });

  test('transpiles YAML with extensions (name, tags, use)', async () => {
    await withTempDir((dir) => {
      writeFileSync(join(dir, 'extended.test.yaml'), `
name: Custom Test Name
tags:
  - smoke
  - auth
use:
  headless: true
  viewport:
    width: 375
    height: 812
goal: Verify mobile login
base_url: https://example.com
statements:
  - intent: Login on mobile
`);

      transpileAllYamlTests({ cwd: dir });

      const code = readFileSync(join(dir, 'extended.yaml.spec.ts'), 'utf-8');

      // Custom name, with tags as a Playwright tag option rather than a title prefix
      expect(code).toContain("test('Custom Test Name', { tag: ['@smoke', '@auth'] }, async (");
      expect(code).not.toContain("test('@smoke");

      // test.use()
      expect(code).toContain('test.use(');
      expect(code).toContain('"headless": true');
      expect(code).toContain('"width": 375');
      expect(code).toContain('"height": 812');
    });
  });

  test('transpiles suite tags from YAML text, at both file and per-test level', async () => {
    // The per-test `tags:` read at yamlParser.ts was dead code until the
    // transpiler started emitting it, and every other suite-tag test builds a
    // ParsedSuite by hand. This exercises the real YAML text -> spec file path,
    // so a parser change that stops reading `tags` fails here.
    await withTempDir((dir) => {
      writeFileSync(join(dir, 'suite.test.yaml'), `
name: Inventory Suite
tags:
  - smoke
base_url: https://example.com
suite:
  tests:
    - name: Sort products
      tags:
        - auth
        - "@slow path"
        - 2026
      statements:
        - intent: Sort by price
    - name: Scalar tag test
      tags: solo
      statements:
        - intent: Do something else
    - name: Untagged test
      statements:
        - intent: Do something
`);

      transpileAllYamlTests({ cwd: dir });

      const code = readFileSync(join(dir, 'suite.yaml.spec.ts'), 'utf-8');

      expect(code).toContain("test.describe.serial('Inventory Suite', { tag: ['@smoke'] }, () => {");
      // Per-test tags emitted; the already-quoted "@slow path" is not doubled,
      // and the unquoted `2026` arrives from the YAML parser as a number — this
      // is the real-text version of the coercion the unit test casts by hand.
      expect(code).toContain("test('Sort products', { tag: ['@auth', '@slow path', '@2026'] }, async (");
      // A bare scalar `tags: solo` behaves like a one-element list, as it does
      // at file level — the two spellings must not diverge.
      expect(code).toContain("test('Scalar tag test', { tag: ['@solo'] }, async (");
      expect(code).toContain("test('Untagged test', async (");
      expect(code).not.toContain('@@');
      expect(code).not.toContain("test('@auth");
    });
  });

  test('base_url emits test.use({ baseURL }) in generated spec', async () => {
    await withTempDir((dir) => {
      writeFileSync(join(dir, 'baseurl.test.yaml'), `
goal: Test with base URL
base_url: https://example.com
statements:
  - URL: /login
  - intent: Enter credentials
`);

      transpileAllYamlTests({ cwd: dir });

      const code = readFileSync(join(dir, 'baseurl.yaml.spec.ts'), 'utf-8');

      // base_url must produce test.use({ baseURL }) so relative URLs resolve
      expect(code).toContain('test.use(');
      expect(code).toContain('"baseURL": "https://example.com"');

      // Should NOT emit page.goto for the base_url itself
      expect(code).not.toContain("page.goto('https://example.com'");
    });
  });

  test('suite base_url emits test.use({ baseURL }) in generated spec', async () => {
    await withTempDir((dir) => {
      writeFileSync(join(dir, 'suite-baseurl.test.yaml'), `
name: Suite with base URL
suite:
  base_url: https://example.com
  tests:
    - name: Login test
      statements:
        - URL: /login
        - intent: Enter credentials
`);

      transpileAllYamlTests({ cwd: dir });

      const code = readFileSync(join(dir, 'suite-baseurl.yaml.spec.ts'), 'utf-8');

      // suite base_url must produce test.use({ baseURL })
      expect(code).toContain('test.use(');
      expect(code).toContain('"baseURL": "https://example.com"');
    });
  });

  test('transpiles YAML with teardown', async () => {
    await withTempDir((dir) => {
      writeFileSync(join(dir, 'teardown.test.yaml'), `
goal: Test with cleanup
base_url: https://example.com
statements:
  - intent: Create a resource
teardown:
  - intent: Delete the resource
`);

      transpileAllYamlTests({ cwd: dir });

      const code = readFileSync(join(dir, 'teardown.yaml.spec.ts'), 'utf-8');

      expect(code).toContain('try {');
      expect(code).toContain('} finally {');
      expect(code).toContain('// Teardown');
      expect(code).toContain('Delete the resource');
    });
  });

  test('transpiles YAML with control flow (IF_ELSE, WHILE, STEP)', async () => {
    await withTempDir((dir) => {
      writeFileSync(join(dir, 'control.test.yaml'), `
goal: Control flow test
base_url: https://example.com
statements:
  - STEP: Login flow
    statements:
      - intent: Enter credentials
      - intent: Click login

  - IF: A cookie banner is visible
    THEN:
      - intent: Click Accept
    ELSE:
      - intent: Continue without clicking

  - WHILE: There are more items
    DO:
      - intent: Process next item
    timeout_ms: 30000
`);

      transpileAllYamlTests({ cwd: dir });

      const code = readFileSync(join(dir, 'control.yaml.spec.ts'), 'utf-8');

      // STEP
      expect(code).toContain('// Step: Login flow');
      expect(code).toContain('Enter credentials');

      // IF_ELSE
      expect(code).toContain('agent.evaluate(page');
      expect(code).toContain('A cookie banner is visible');
      expect(code).toContain('} else {');

      // WHILE
      expect(code).toContain('Date.now()');
      expect(code).toContain('30000');
      expect(code).toContain('There are more items');
    });
  });

  test('transpiles YAML with variables', async () => {
    await withTempDir((dir) => {
      writeFileSync(join(dir, 'vars.test.yaml'), `
goal: Variable interpolation test
statements:
  - URL: https://example.com
  - action: input_text
    description: Type username
    locator: "getByLabel('Username')"
    text: "{{TEST_USER}}"
`);

      transpileAllYamlTests({ cwd: dir });

      const code = readFileSync(join(dir, 'vars.yaml.spec.ts'), 'utf-8');

      // Variables are passed through as literal {{VAR}} for runtime resolution
      expect(code).toContain('{{TEST_USER}}');
    });
  });

  test('transpiles YAML with template expansion', async () => {
    await withTempDir((dir) => {
      // Create template
      mkdirSync(join(dir, 'templates'), { recursive: true });
      writeFileSync(join(dir, 'templates', 'login.yaml'), `
params:
  - username
  - password
statements:
  - action: input_text
    intent: "Enter <<username>>"
    locator: "getByLabel('Username')"
    text: "<<username>>"
  - action: input_text
    intent: "Enter <<password>>"
    locator: "getByLabel('Password')"
    text: "<<password>>"
  - action: click
    intent: Click login
    locator: "getByRole('button', { name: 'Log in' })"
`);

      // Create test that uses template
      writeFileSync(join(dir, 'with-template.test.yaml'), `
goal: Login with template
statements:
  - URL: https://example.com
  - template: ./templates/login.yaml
    params:
      username: "<<TEST_USER>>"
      password: "<<TEST_PASS>>"
  - VERIFY: Dashboard is visible
`);

      transpileAllYamlTests({ cwd: dir });

      const code = readFileSync(join(dir, 'with-template.yaml.spec.ts'), 'utf-8');

      // Template params with variables should be in generated code
      expect(code).toContain('<<TEST_USER>>');
      expect(code).toContain('<<TEST_PASS>>');

      // Template's action locators should appear
      expect(code).toContain("getByLabel('Username')");
      expect(code).toContain("getByLabel('Password')");
      expect(code).toContain("getByRole('button', { name: 'Log in' })");

      // VERIFY from the main file
      expect(code).toContain('Dashboard is visible');
    });
  });

  test('discovers YAML files in subdirectories', async () => {
    await withTempDir((dir) => {
      mkdirSync(join(dir, 'auth'), { recursive: true });
      mkdirSync(join(dir, 'checkout'), { recursive: true });

      writeFileSync(join(dir, 'auth', 'login.test.yaml'), `
goal: Login
base_url: https://example.com
statements:
  - intent: Login
`);
      writeFileSync(join(dir, 'checkout', 'purchase.test.yaml'), `
goal: Purchase
base_url: https://example.com
statements:
  - intent: Purchase
`);

      transpileAllYamlTests({ cwd: dir });

      expect(existsSync(join(dir, 'auth', 'login.yaml.spec.ts'))).toBe(true);
      expect(existsSync(join(dir, 'checkout', 'purchase.yaml.spec.ts'))).toBe(true);
    });
  });

  test.describe('caching', () => {
    test('skips transpilation when output is up-to-date', async () => {
      await withTempDir((dir) => {
        writeFileSync(join(dir, 'cached.test.yaml'), `
goal: Cache test
base_url: https://example.com
statements:
  - intent: Step one
`);

        // First run: generates the file
        transpileAllYamlTests({ cwd: dir });
        const outPath = join(dir, 'cached.yaml.spec.ts');
        expect(existsSync(outPath)).toBe(true);

        const firstContent = readFileSync(outPath, 'utf-8');
        const firstMtime = statSync(outPath).mtimeMs;

        // Small delay to ensure mtime would differ if rewritten
        const past = new Date(Date.now() - 2000);
        utimesSync(join(dir, 'cached.test.yaml'), past, past);

        // Second run: should skip (YAML is older than output)
        transpileAllYamlTests({ cwd: dir });
        const secondMtime = statSync(outPath).mtimeMs;
        const secondContent = readFileSync(outPath, 'utf-8');

        expect(secondMtime).toBe(firstMtime);
        expect(secondContent).toBe(firstContent);
      });
    });

    test('re-transpiles a spec generated under an older output-format revision', async () => {
        // The whole point of OUTPUT_FORMAT_REVISION: when the emitted code
        // changes shape but the package version has not moved (it is always
        // `dev` from source), only the header can invalidate the cached spec.
        // Without this, a spec still carrying the old `test('@smoke X', ...)`
        // form is kept forever and CI runs code the YAML no longer describes.
        await withTempDir((dir) => {
          writeFileSync(join(dir, 'fmt.test.yaml'), `
goal: Format revision test
base_url: https://example.com
statements:
  - intent: Step one
`);

          transpileAllYamlTests({ cwd: dir });
          const outPath = join(dir, 'fmt.yaml.spec.ts');
          const current = readFileSync(outPath, 'utf-8');

          // Same package version, older format revision. The spec's mtime stays
          // newer than the YAML, so mtime alone would keep it.
          writeFileSync(
            outPath,
            current.replace(/^\/\/ @generated by shiplightai v.*$/m, '// @generated by shiplightai vdev+fmt1'),
          );
          const past = new Date(Date.now() - 5000);
          utimesSync(join(dir, 'fmt.test.yaml'), past, past);

          transpileAllYamlTests({ cwd: dir });

          expect(readFileSync(outPath, 'utf-8')).toBe(current);
      });
    });

    test('re-transpiles when YAML source changes', async () => {
      await withTempDir((dir) => {
        writeFileSync(join(dir, 'changing.test.yaml'), `
goal: Original
base_url: https://example.com
statements:
  - intent: Original step
`);

        transpileAllYamlTests({ cwd: dir });
        const outPath = join(dir, 'changing.yaml.spec.ts');
        const firstContent = readFileSync(outPath, 'utf-8');
        expect(firstContent).toContain('Original');

        // Set the output file's mtime to the past so the source is newer
        const past = new Date(Date.now() - 5000);
        utimesSync(outPath, past, past);

        // Modify the YAML source (touch it to update mtime)
        writeFileSync(join(dir, 'changing.test.yaml'), `
goal: Updated
base_url: https://example.com
statements:
  - intent: Updated step
`);

        transpileAllYamlTests({ cwd: dir });
        const secondContent = readFileSync(outPath, 'utf-8');
        expect(secondContent).toContain('Updated');
        expect(secondContent).not.toContain("test('Original'");
      });
    });

    test('re-transpiles when referenced template changes', async () => {
      await withTempDir((dir) => {
        const templatePath = join(dir, 'shared.yaml');
        writeFileSync(templatePath, `
statements:
  - intent: Original template step
`);

        writeFileSync(join(dir, 'uses-template.test.yaml'), `
goal: Template cache test
base_url: https://example.com
statements:
  - template: ./shared.yaml
`);

        transpileAllYamlTests({ cwd: dir });
        const outPath = join(dir, 'uses-template.yaml.spec.ts');
        const firstContent = readFileSync(outPath, 'utf-8');
        expect(firstContent).toContain('Original template step');

        // Set output mtime to past
        const past = new Date(Date.now() - 5000);
        utimesSync(outPath, past, past);

        // Update the template (newer mtime than output)
        writeFileSync(templatePath, `
statements:
  - intent: Updated template step
`);

        transpileAllYamlTests({ cwd: dir });
        const secondContent = readFileSync(outPath, 'utf-8');
        expect(secondContent).toContain('Updated template step');
      });
    });
  });

  test('handles invalid YAML gracefully — transpiles valid files and skips bad ones', async () => {
    await withTempDir((dir) => {
      // Valid file
      writeFileSync(join(dir, 'good.test.yaml'), `
goal: Good test
base_url: https://example.com
statements:
  - intent: Do something
`);

      // Invalid file (missing required fields)
      writeFileSync(join(dir, 'bad.test.yaml'), `
not_a_valid_field: true
`);

      // Global scan (no specific files requested) — warns and skips bad files.
      // When specific files are requested (e.g. CLI `--files bad.test.yaml`),
      // transpileAllYamlTests still throws for those. The skip-and-continue
      // behavior only applies to discovery scans so one bad file doesn't block
      // the entire project from transpiling.
      transpileAllYamlTests({ cwd: dir });

      // Good file should still be transpiled
      expect(existsSync(join(dir, 'good.yaml.spec.ts'))).toBe(true);

      // Bad file should not produce output
      expect(existsSync(join(dir, 'bad.yaml.spec.ts'))).toBe(false);
    });
  });

  test('generates syntactically valid TypeScript', async () => {
    await withTempDir((dir) => {
      // Complex YAML with multiple features
      writeFileSync(join(dir, 'complex.test.yaml'), `
name: Complex E2E Test
tags:
  - regression
use:
  locale: fr-FR
goal: Full feature test
base_url: https://example.com
statements:
  - STEP: Setup
    statements:
      - intent: Navigate to the app
      - VERIFY: App is loaded

  - intent: Click Submit
    action: click
    locator: "getByRole('button', { name: 'Submit' })"

  - IF: "js: page.url().includes('/success')"
    THEN:
      - VERIFY: Success page is shown
    ELSE:
      - intent: Retry the submission

teardown:
  - intent: Clean up test data
`);

      transpileAllYamlTests({ cwd: dir });

      const code = readFileSync(join(dir, 'complex.yaml.spec.ts'), 'utf-8');

      // Check structural validity: balanced braces
      const opens = (code.match(/\{/g) || []).length;
      const closes = (code.match(/\}/g) || []).length;
      expect(opens).toBe(closes);

      // Check structural validity: balanced parens
      const openParens = (code.match(/\(/g) || []).length;
      const closeParens = (code.match(/\)/g) || []).length;
      expect(openParens).toBe(closeParens);

      // Ends properly
      expect(code.trimEnd()).toMatch(/\}\);$/);
    });
  });
});
