/**
 * Global Event Bus for cross-component communication
 * Uses mitt for lightweight event handling
 */

import mitt from 'mitt';
import { useEffect } from 'react';

// Define event types and their payloads
export type AppEvents = {
  // Locator Picker Events
  'locator:request-pick': {
    statementId: string;
    language?: 'JavaScript' | 'Python' | 'C#' | 'Java';
  };
  'locator:picked': {
    statementId: string;
    locator: string;
    language: string;
  };
  'locator:pick-cancelled': {
    statementId: string;
  };
  
  // Toolbar Events
  // eslint-disable-next-line @typescript-eslint/no-empty-object-type
  'toolbar:picker-requested': {
    // Emitted when toolbar picker button is clicked
    // Components with DebuggerContext should listen and emit 'locator:request-pick'
  };
  
  // Recorder Events
  'recorder:action-recorded': {
    actionEntity: any; // ActionEntity from shiplight-types
    statementUid: string; // The UID generated by MultiPageViewer for this statement
  };
  'recorder:action-updated': {
    actionEntity: any; // ActionEntity from shiplight-types
    statementUid?: string; // The UID of the statement to update
  };
  
  // Debugger Events
  'debugger:reset-session-requested': {
    reason: 'timeout' | 'external';
    showTimeoutBannerAfterReset?: boolean;
  };
  'debugger:reset-session-completed': {
    reason: 'timeout' | 'external';
    showTimeoutBanner?: boolean;
  };
};

// Create the global event bus instance
export const appEventBus = mitt<AppEvents>();

// Helper hook for React components to use the event bus with cleanup
export function useAppEvent<K extends keyof AppEvents>(
  event: K,
  handler: (payload: AppEvents[K]) => void,
  deps: React.DependencyList = []
) {
  useEffect(() => {
    // @ts-ignore - mitt's typing is a bit strict here
    appEventBus.on(event, handler);

    return () => {
      // @ts-ignore
      appEventBus.off(event, handler);
    };
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, deps);
}

// Debug helper (only in development)
if (process.env.NODE_ENV === 'development') {
  // Log all events for debugging
  appEventBus.on('*', (type, payload) => {
    console.log(`🚌 Event Bus: ${type}`, payload);
  });

  // Expose to window for debugging
  if (typeof window !== 'undefined') {
    (window as any).appEventBus = appEventBus;
  }
}
