import { describe, it, after } from 'node:test';
import * as assert from 'node:assert/strict';
import { transpileYamlContent } from './pipeline';
import { expandTemplates } from './templates';
import { parseYamlTestFile } from './yamlParser';
import type { Step } from 'shiplight-types';
import { writeFileSync, mkdirSync, readFileSync, rmSync } from 'fs';
import { join } from 'path';
import { tmpdir } from 'os';

const tmpDir = join(tmpdir(), 'yaml-transpiler-test-' + Date.now());

describe('transpileYamlContent', () => {
  mkdirSync(tmpDir, { recursive: true });

  after(() => {
    rmSync(tmpDir, { recursive: true, force: true });
  });

  it('transpiles a simple test and writes .yaml.spec.ts', () => {
    const yaml = `
goal: Login test
statements:
  - action: go_to_url
    intent: Navigate to login page
    url: https://example.com/login
    locator: "page"
    xpath: html/body
  - action: click
    intent: Click login button
    locator: "getByRole('button', { name: 'Login' })"
    xpath: html/body/div/button
`;
    const filePath = join(tmpDir, 'simple.test.yaml');
    writeFileSync(filePath, yaml);

    const result = transpileYamlContent(yaml, filePath, { version: '0.0.1-test' });

    assert.equal(result.valid, true);
    assert.deepEqual(result.errors, []);
    assert.ok(result.specFile);

    const content = readFileSync(result.specFile!, 'utf-8');
    assert.ok(content.includes('shiplightai/fixture'));
    assert.ok(content.includes('Login test'));
    assert.ok(content.includes('@generated by shiplightai v0.0.1-test'));
  });

  it('returns errors for invalid YAML', () => {
    const yaml = `not: valid: yaml: [`;
    const filePath = join(tmpDir, 'invalid.test.yaml');

    const result = transpileYamlContent(yaml, filePath);

    assert.equal(result.valid, false);
    assert.ok(result.errors.length > 0);
  });

  it('returns errors for bad JS syntax in VERIFY', () => {
    const yaml = `
goal: Test bad JS
statements:
  - VERIFY: Check URL
    js: "await expect(page).toHaveURL(//bad/, { timeout: 5000 })"
`;
    const filePath = join(tmpDir, 'badjs.test.yaml');

    const result = transpileYamlContent(yaml, filePath);

    assert.equal(result.valid, false);
    assert.ok(result.errors.length > 0);
  });

  it('transpiles description+js code steps wrapped in agent.step()', () => {
    const yaml = `
goal: Test js code steps
statements:
  - description: Click the button
    js: "await page.getByRole('button', { name: 'Submit' }).first().click({ timeout: 5000 })"
  - description: Type in input
    js: "await page.getByLabel('Email').first().fill('test@test.com', { timeout: 5000 })"
  - description: Press Enter
    js: "await page.keyboard.press('Enter')"
  - description: Wait for results
    js: "await page.waitForTimeout(2000)"
`;
    const filePath = join(tmpDir, 'js-shorthand.test.yaml');
    writeFileSync(filePath, yaml);

    const result = transpileYamlContent(yaml, filePath, { version: '0.0.1-test' });

    assert.equal(result.valid, true);
    assert.deepEqual(result.errors, []);
    assert.ok(result.specFile);

    const content = readFileSync(result.specFile!, 'utf-8');
    // Should use agent.step() wrapper (not agent.run())
    assert.ok(content.includes('agent.step(page, async () =>'));
    assert.ok(!content.includes('agent.run('));
    // Should contain raw JS from js: field
    assert.ok(content.includes("page.getByRole('button', { name: 'Submit' })"));
    assert.ok(content.includes("page.getByLabel('Email')"));
    assert.ok(content.includes("page.keyboard.press('Enter')"));
    assert.ok(content.includes('page.waitForTimeout(2000)'));
    // js_code does not self-heal — selfHealable=false
    assert.ok(content.includes(', false);'));
  });

  it('does not enable self-healing for go_to_url steps', () => {
    const yaml = `
goal: Navigate without healing
statements:
  - URL: /login
`;
    const filePath = join(tmpDir, 'go-to-url-no-self-heal.test.yaml');
    writeFileSync(filePath, yaml);

    const result = transpileYamlContent(yaml, filePath, { version: '0.0.1-test' });

    assert.equal(result.valid, true);
    assert.deepEqual(result.errors, []);
    assert.ok(result.specFile);

    const content = readFileSync(result.specFile, 'utf-8');
    const stepCallEnd = content
      .split('\n')
      .find((line) => line.includes('}, "Navigate to /login"'));
    assert.ok(stepCallEnd, 'generated spec should wrap go_to_url in agent.step()');
    assert.match(stepCallEnd, /, false\);$/);
  });

  it('destructures extensionActionPopup when referenced by a js code step', () => {
    const yaml = `
goal: Test the real extension toolbar popup with JavaScript
statements:
  - description: Verify the popup is recording
    js: "await expect(extensionActionPopup.getByText('Recording')).toBeVisible()"
`;
    const filePath = join(tmpDir, 'js-extension-popup.test.yaml');
    writeFileSync(filePath, yaml);

    const result = transpileYamlContent(yaml, filePath, { version: '0.0.1-test' });

    assert.equal(result.valid, true);
    assert.deepEqual(result.errors, []);
    assert.ok(result.specFile);

    const content = readFileSync(result.specFile!, 'utf-8');
    assert.ok(content.includes('{ page, agent, extensionActionPopup }'));
    assert.ok(content.includes("expect(extensionActionPopup.getByText('Recording'))"));
  });

  it('excludes description+js (js_code) from coverage stats', () => {
    const yaml = `
goal: Test js coverage
statements:
  - intent: Click the submit button
    action: click
    locator: "getByRole('button', { name: 'Submit' })"
  - description: Wait (no locator)
    js: "await page.waitForTimeout(1000)"
`;
    const filePath = join(tmpDir, 'js-coverage.test.yaml');
    writeFileSync(filePath, yaml);

    const result = transpileYamlContent(yaml, filePath);

    assert.equal(result.valid, true);
    assert.ok(result.stats);
    // description+js (js_code) is a non-intent shorthand → excluded; only the structured action counts
    assert.equal(result.stats!.total, 1);
    assert.equal(result.stats!.action, 1);
    assert.equal(result.stats!.draft, 0);
    assert.equal(result.stats!.coverage, 100);
  });

  it('validates JS syntax in description+js code steps', () => {
    const yaml = `
goal: Test bad js code step
statements:
  - description: Bad JS
    js: "await page.click(//bad/)"
`;
    const filePath = join(tmpDir, 'bad-js-shorthand.test.yaml');

    const result = transpileYamlContent(yaml, filePath);

    assert.equal(result.valid, false);
    assert.ok(result.errors.length > 0);
  });

  // -------------------------------------------------------------------------
  // Function call: syntax
  // -------------------------------------------------------------------------

  it('transpiles call: with args: [page]', () => {
    const yaml = `
goal: Test function args
statements:
  - intent: Clear the cart
    call: "../helpers/cart.ts#clearCart"
    args: [page]
`;
    const filePath = join(tmpDir, 'func-args.test.yaml');
    writeFileSync(filePath, yaml);

    const result = transpileYamlContent(yaml, filePath, { version: '0.0.1-test' });

    assert.equal(result.valid, true);
    assert.ok(result.specFile);

    const content = readFileSync(result.specFile!, 'utf-8');
    assert.ok(content.includes("import { clearCart } from '../helpers/cart'"));
    assert.ok(content.includes('await clearCart(page)'));
  });

  it('transpiles call: with mixed arg types', () => {
    const yaml = `
goal: Test mixed function args
statements:
  - intent: Verify count
    call: "../helpers/cart.ts#verifyCartCount"
    args: [page, 2, "expected two items"]
`;
    const filePath = join(tmpDir, 'func-mixed-args.test.yaml');
    writeFileSync(filePath, yaml);

    const result = transpileYamlContent(yaml, filePath, { version: '0.0.1-test' });

    assert.equal(result.valid, true);
    assert.ok(result.specFile);

    const content = readFileSync(result.specFile!, 'utf-8');
    assert.ok(content.includes("import { verifyCartCount } from '../helpers/cart'"));
    assert.ok(content.includes('await verifyCartCount(page, 2, "expected two items")'));
  });

  it('transpiles call: with no args', () => {
    const yaml = `
goal: Test no-arg function
statements:
  - intent: Run cleanup
    call: "../helpers/utils.ts#cleanup"
`;
    const filePath = join(tmpDir, 'func-no-args.test.yaml');
    writeFileSync(filePath, yaml);

    const result = transpileYamlContent(yaml, filePath, { version: '0.0.1-test' });

    assert.equal(result.valid, true);
    assert.ok(result.specFile);

    const content = readFileSync(result.specFile!, 'utf-8');
    assert.ok(content.includes("import { cleanup } from '../helpers/utils'"));
    assert.ok(content.includes('await cleanup()'));
  });

  it('transpiles call: with $variable args', () => {
    const yaml = `
goal: Test variable args
statements:
  - intent: Create user
    call: "../helpers/users.ts#createUser"
    args: [page, $savedEmail]
`;
    const filePath = join(tmpDir, 'func-var-args.test.yaml');
    writeFileSync(filePath, yaml);

    const result = transpileYamlContent(yaml, filePath, { version: '0.0.1-test' });

    assert.equal(result.valid, true);
    assert.ok(result.specFile);

    const content = readFileSync(result.specFile!, 'utf-8');
    assert.ok(content.includes("import { createUser } from '../helpers/users'"));
    assert.ok(content.includes("await createUser(page, agent.agentServices.readVariable('savedEmail'))"));
  });

  it('destructures testContext when used as a function arg', () => {
    const yaml = `
goal: Test testContext fixture
statements:
  - intent: Return credentials
    call: "../helpers/auth.ts#returnCredentials"
    args: [page, testContext]
`;
    const filePath = join(tmpDir, 'func-testcontext.test.yaml');
    writeFileSync(filePath, yaml);

    const result = transpileYamlContent(yaml, filePath, { version: '0.0.1-test' });

    assert.equal(result.valid, true);
    assert.ok(result.specFile);

    const content = readFileSync(result.specFile!, 'utf-8');
    assert.ok(content.includes('{ page, agent, testContext }'));
    assert.ok(content.includes('await returnCredentials(page, testContext)'));
  });

  it('destructures request when used as a function arg', () => {
    const yaml = `
goal: Test request fixture
statements:
  - intent: Make API call
    call: "../helpers/api.ts#callApi"
    args: [request, page]
`;
    const filePath = join(tmpDir, 'func-request.test.yaml');
    writeFileSync(filePath, yaml);

    const result = transpileYamlContent(yaml, filePath, { version: '0.0.1-test' });

    assert.equal(result.valid, true);
    assert.ok(result.specFile);

    const content = readFileSync(result.specFile!, 'utf-8');
    assert.ok(content.includes('{ page, agent, request }'));
    assert.ok(content.includes('await callApi(request, page)'));
  });

  it('destructures extensionActionPopup when used as a function arg', () => {
    const yaml = `
goal: Test a real extension toolbar popup
statements:
  - intent: Prepare the real extension popup
    call: "helpers/recorder.ts#preparePopup"
    args: [page, extensionActionPopup]
`;
    const filePath = join(tmpDir, 'extension-popup.test.yaml');
    writeFileSync(filePath, yaml);

    const result = transpileYamlContent(yaml, filePath, { version: '0.0.1-test' });

    assert.equal(result.valid, true);
    assert.ok(result.specFile);

    const content = readFileSync(result.specFile!, 'utf-8');
    assert.ok(content.includes('{ page, agent, extensionActionPopup }'));
    assert.ok(content.includes('await preparePopup(page, extensionActionPopup)'));
  });

  it('resolves bare function path relative to projectRoot and emits correct relative import', () => {
    // yaml is in <tmpDir>/tests/sub/, projectRoot is tmpDir
    // helpers/auth is a bare path → should resolve to <tmpDir>/helpers/auth
    // relative from <tmpDir>/tests/sub/ → ../../helpers/auth (not ./../../../helpers/auth)
    const subDir = join(tmpDir, 'tests', 'sub');
    mkdirSync(subDir, { recursive: true });
    const yaml = `
goal: Test bare path resolution
statements:
  - intent: Dismiss modal
    action: function
    functionName: helpers/auth.ts#loginUser
    parameterNames:
      - page
    parameterValues:
      - page
`;
    const filePath = join(subDir, 'bare-path.test.yaml');
    writeFileSync(filePath, yaml);

    const result = transpileYamlContent(yaml, filePath, {
      version: '0.0.1-test',
      projectRoot: tmpDir,
    });

    assert.equal(result.valid, true);
    assert.ok(result.specFile);
    const content = readFileSync(result.specFile!, 'utf-8');
    // Must be a proper relative path, not a bare package name, and not ./../
    assert.ok(
      content.includes("import { loginUser } from '../../helpers/auth'"),
      `expected relative import, got: ${content.match(/import \{[^}]+\}[^\n]+/)?.[0]}`,
    );
    assert.ok(content.includes('await loginUser(page)'));
  });

  it('resolves bare function path in same directory as yaml file', () => {
    // yaml in tmpDir directly, helpers/auth resolves to <tmpDir>/helpers/auth
    // relative from tmpDir → ./helpers/auth
    const yaml = `
goal: Test bare path same dir
statements:
  - intent: Login
    action: function
    functionName: helpers/auth.ts#loginUser
    parameterNames:
      - page
    parameterValues:
      - page
`;
    const filePath = join(tmpDir, 'bare-same-dir.test.yaml');
    writeFileSync(filePath, yaml);

    const result = transpileYamlContent(yaml, filePath, {
      version: '0.0.1-test',
      projectRoot: tmpDir,
    });

    assert.equal(result.valid, true);
    assert.ok(result.specFile);
    const content = readFileSync(result.specFile!, 'utf-8');
    assert.ok(
      content.includes("import { loginUser } from './helpers/auth'"),
      `expected ./helpers/auth import, got: ${content.match(/import \{[^}]+\}[^\n]+/)?.[0]}`,
    );
  });

  it('keeps ../-relative function path relative to the yaml file even when projectRoot is set', () => {
    // Regression (release gate, ShiplightAI/examples): a `../helpers/...` path in
    // a YAML nested one level deep must stay relative to the YAML/spec file, NOT
    // be re-resolved against projectRoot. Re-resolving escaped above the project
    // root and added an extra '..' (`../../helpers/...`), producing a
    // module-not-found error. yaml is in <tmpDir>/demo/, helpers live at
    // <tmpDir>/helpers/, so `../helpers/cart.ts` from demo/ points at the spec's
    // sibling `../helpers/cart` — the co-located spec resolves it correctly.
    const subDir = join(tmpDir, 'demo');
    mkdirSync(subDir, { recursive: true });
    const yaml = `
goal: Test ../-relative path with projectRoot set
statements:
  - intent: Clear the cart
    call: "../helpers/cart.ts#clearCart"
    args: [page]
`;
    const filePath = join(subDir, 'rel-path-subdir.test.yaml');
    writeFileSync(filePath, yaml);

    const result = transpileYamlContent(yaml, filePath, {
      version: '0.0.1-test',
      projectRoot: tmpDir,
    });

    assert.equal(result.valid, true);
    assert.ok(result.specFile);
    const content = readFileSync(result.specFile!, 'utf-8');
    assert.ok(
      content.includes("import { clearCart } from '../helpers/cart'"),
      `expected ../helpers/cart import, got: ${content.match(/import \{[^}]+\}[^\n]+/)?.[0]}`,
    );
    assert.ok(content.includes('await clearCart(page)'));
  });

  it('emits bare path as-is when projectRoot is not provided', () => {
    const yaml = `
goal: Test bare path no projectRoot
statements:
  - intent: Login
    action: function
    functionName: helpers/auth.ts#loginUser
    parameterNames:
      - page
    parameterValues:
      - page
`;
    const filePath = join(tmpDir, 'bare-no-root.test.yaml');
    writeFileSync(filePath, yaml);

    const result = transpileYamlContent(yaml, filePath, { version: '0.0.1-test' });

    assert.equal(result.valid, true);
    assert.ok(result.specFile);
    const content = readFileSync(result.specFile!, 'utf-8');
    // Without projectRoot the path is emitted as-is (bare)
    assert.ok(content.includes("import { loginUser } from 'helpers/auth'"));
  });

  it('destructures request via parameterValues and emits it in fixture and call', () => {
    const yaml = `
goal: Test parameterValues with request
statements:
  - intent: Dismiss modal
    action: function
    functionName: helpers/dismiss.ts#dismissModal
    parameterNames:
      - page
      - testContext
      - request
    parameterValues:
      - page
      - testContext
      - request
`;
    const filePath = join(tmpDir, 'func-parametervalues-request.test.yaml');
    writeFileSync(filePath, yaml);

    const result = transpileYamlContent(yaml, filePath, { version: '0.0.1-test' });

    assert.equal(result.valid, true);
    assert.ok(result.specFile);
    const content = readFileSync(result.specFile!, 'utf-8');
    // request and testContext must appear in the fixture destructure
    assert.ok(
      content.includes('{ page, agent, request, testContext }'),
      `expected fixture destructure with request and testContext, got: ${content.match(/async \([^)]+\)/)?.[0]}`,
    );
    // All three system params should be passed through
    assert.ok(content.includes('await dismissModal(page, testContext, request)'));
  });

  it('destructures both testContext and request when both are used', () => {
    const yaml = `
goal: Test multiple extra fixtures
statements:
  - intent: Setup auth
    call: "../helpers/auth.ts#setupAuth"
    args: [page, testContext]
  - intent: Make API call
    call: "../helpers/api.ts#callApi"
    args: [request]
`;
    const filePath = join(tmpDir, 'func-both-extras.test.yaml');
    writeFileSync(filePath, yaml);

    const result = transpileYamlContent(yaml, filePath, { version: '0.0.1-test' });

    assert.equal(result.valid, true);
    assert.ok(result.specFile);

    const content = readFileSync(result.specFile!, 'utf-8');
    assert.ok(content.includes('{ page, agent, request, testContext }'));
  });

  it('does not add extra fixtures when only page and agent are used', () => {
    const yaml = `
goal: Test no extra fixtures
statements:
  - intent: Clear the cart
    call: "../helpers/cart.ts#clearCart"
    args: [page]
`;
    const filePath = join(tmpDir, 'func-no-extras.test.yaml');
    writeFileSync(filePath, yaml);

    const result = transpileYamlContent(yaml, filePath, { version: '0.0.1-test' });

    assert.equal(result.valid, true);
    assert.ok(result.specFile);

    const content = readFileSync(result.specFile!, 'utf-8');
    assert.ok(content.includes('{ page, agent }'));
    assert.ok(!content.includes('testContext'));
    assert.ok(!content.includes('request'));
  });

  it('transpiles IF with js: condition using agent.agentServices', () => {
    const yaml = `
goal: Test IF with js condition
statements:
  - IF: "js:(await agent.agentServices.readVariable('group_verified')) === 'true'"
    THEN:
      - VERIFY: The group is verified
`;
    const filePath = join(tmpDir, 'if-js-agent.test.yaml');
    writeFileSync(filePath, yaml);

    const result = transpileYamlContent(yaml, filePath, { version: '0.0.1-test' });

    assert.equal(result.valid, true);
    assert.deepEqual(result.errors, []);
    assert.ok(result.specFile);

    const content = readFileSync(result.specFile!, 'utf-8');
    // JS_CODE condition should be inlined directly (not wrapped in agent.evaluate())
    assert.ok(
      content.includes("if ((await agent.agentServices.readVariable('group_verified')) === 'true')"),
      'IF js: condition should inline agent.agentServices.readVariable() call',
    );
    assert.ok(
      !content.includes('agent.evaluate'),
      'JS_CODE condition should NOT use agent.evaluate()',
    );
  });

  it('transpiles WHILE with js: condition using agent.agentServices', () => {
    const yaml = `
goal: Test WHILE with js condition
statements:
  - WHILE: "js:(await agent.agentServices.readVariable('retries')) !== 'done'"
    DO:
      - intent: Retry the operation
        action: click
        locator: "getByRole('button', { name: 'Retry' }).first()"
`;
    const filePath = join(tmpDir, 'while-js-agent.test.yaml');
    writeFileSync(filePath, yaml);

    const result = transpileYamlContent(yaml, filePath, { version: '0.0.1-test' });

    assert.equal(result.valid, true);
    assert.deepEqual(result.errors, []);
    assert.ok(result.specFile);

    const content = readFileSync(result.specFile!, 'utf-8');
    // JS_CODE condition should be inlined directly
    assert.ok(
      content.includes("(await agent.agentServices.readVariable('retries')) !== 'done'"),
      'WHILE js: condition should inline agent.agentServices.readVariable() call',
    );
    assert.ok(
      !content.includes('agent.evaluate'),
      'JS_CODE condition should NOT use agent.evaluate()',
    );
  });

  it('transpiles AI-mode IF condition with the "if" construct tag', () => {
    const yaml = `
goal: Test AI IF condition
statements:
  - IF: The group is verified
    THEN:
      - VERIFY: The dashboard is shown
`;
    const filePath = join(tmpDir, 'if-ai-tag.test.yaml');
    writeFileSync(filePath, yaml);

    const result = transpileYamlContent(yaml, filePath, { version: '0.0.1-test' });

    assert.equal(result.valid, true);
    assert.deepEqual(result.errors, []);
    assert.ok(result.specFile);

    const content = readFileSync(result.specFile!, 'utf-8');
    // AI condition must route through agent.evaluate...
    assert.ok(
      content.includes('await agent.evaluate(page, "The group is verified"'),
      'AI IF condition should call agent.evaluate()',
    );
    // ...and carry the "if" construct tag as the 4th arg so runtime attributes
    // it to evaluate_if (guards the statements.ts emit against silent reverts).
    assert.ok(
      content.includes(', "if")'),
      'AI IF condition should emit the "if" construct tag as the 4th agent.evaluate arg',
    );
  });

  it('transpiles AI-mode WHILE condition with the "while" construct tag', () => {
    const yaml = `
goal: Test AI WHILE condition
statements:
  - WHILE: The list is still loading
    DO:
      - intent: Wait for more items
        action: click
        locator: "getByRole('button', { name: 'Load more' }).first()"
`;
    const filePath = join(tmpDir, 'while-ai-tag.test.yaml');
    writeFileSync(filePath, yaml);

    const result = transpileYamlContent(yaml, filePath, { version: '0.0.1-test' });

    assert.equal(result.valid, true);
    assert.deepEqual(result.errors, []);
    assert.ok(result.specFile);

    const content = readFileSync(result.specFile!, 'utf-8');
    // AI loop condition must route through agent.evaluate...
    assert.ok(
      content.includes('await agent.evaluate(page, "The list is still loading"'),
      'AI WHILE condition should call agent.evaluate()',
    );
    // ...and carry the "while" construct tag as the 4th arg so runtime attributes
    // it to evaluate_while rather than collapsing into evaluate_if.
    assert.ok(
      content.includes(', "while")'),
      'AI WHILE condition should emit the "while" construct tag as the 4th agent.evaluate arg',
    );
  });

  it('returns warnings for low action coverage (too many drafts)', () => {
    const yaml = `
goal: Test with mostly drafts
statements:
  - intent: Click something
  - intent: Click another thing
  - intent: Fill in the form
`;
    const filePath = join(tmpDir, 'drafts.test.yaml');
    writeFileSync(filePath, yaml);

    const result = transpileYamlContent(yaml, filePath);

    assert.equal(result.valid, true);
    assert.ok(result.warnings.length > 0);
    assert.equal(result.stats!.draft, 3);
    assert.equal(result.stats!.action, 0);
    assert.equal(result.stats!.coverage, 0);
    assert.ok(result.specFile);
  });

  it('transpiles parameterized tests with {{}} variables instead of <<>> substitution', () => {
    const yaml = `
goal: Add product to cart
parameters:
  - name: backpack
    values:
      product_name: Sauce Labs Backpack
  - name: bike light
    values:
      product_name: Sauce Labs Bike Light
statements:
  - action: go_to_url
    intent: Navigate to inventory
    url: /inventory.html
    locator: "page"
    xpath: html/body
  - VERIFY: "{{product_name}} is in the cart"
`;
    const filePath = join(tmpDir, 'parameterized.test.yaml');
    writeFileSync(filePath, yaml);

    const result = transpileYamlContent(yaml, filePath, { version: '0.0.1-test' });

    assert.equal(result.valid, true);
    assert.deepEqual(result.errors, []);
    assert.ok(result.specFile);

    const content = readFileSync(result.specFile!, 'utf-8');

    // Should generate two separate test blocks
    assert.ok(content.includes('[backpack]'));
    assert.ok(content.includes('[bike light]'));

    // Should emit saveVariable calls, NOT <<>> string replacement
    assert.ok(
      content.includes(`agent.agentServices.saveVariable("product_name", "Sauce Labs Backpack")`),
      'should set product_name variable for backpack param set',
    );
    assert.ok(
      content.includes(`agent.agentServices.saveVariable("product_name", "Sauce Labs Bike Light")`),
      'should set product_name variable for bike light param set',
    );

    // {{product_name}} should be preserved in the generated code (resolved at runtime)
    assert.ok(
      content.includes('{{product_name}} is in the cart'),
      '{{product_name}} should be preserved for runtime variable resolution',
    );
  });
});

// ============================================================================
// expandTemplates — wraps template references in a STEP with template_path
// ============================================================================

const templateTmpDir = join(tmpdir(), 'expand-templates-test-' + Date.now());

describe('expandTemplates', () => {
  mkdirSync(join(templateTmpDir, 'templates'), { recursive: true });

  after(() => {
    rmSync(templateTmpDir, { recursive: true, force: true });
  });

  it('wraps template reference in a STEP with template_path', () => {
    // Create a template file
    writeFileSync(join(templateTmpDir, 'templates', 'login.yaml'), `
name: Login
params:
  - username
statements:
  - intent: Enter <<username>>
  - intent: Click login
`);

    const doc = {
      goal: 'test',
      statements: [
        { template: './templates/login.yaml', params: { username: 'admin' } },
      ],
    };

    const sourceFile = join(templateTmpDir, 'test.yaml');
    writeFileSync(sourceFile, '');
    const result = expandTemplates(doc, sourceFile);

    // Should have one statement (the STEP wrapper)
    assert.equal(result.doc.statements.length, 1);

    const step = result.doc.statements[0];
    assert.equal(step.STEP, 'Login');
    assert.equal(step.template_path, './templates/login.yaml');
    assert.deepEqual(step.template_params, { username: 'admin' });

    // Child statements should be expanded with params substituted
    assert.equal(step.statements.length, 2);
    assert.equal(step.statements[0].intent, 'Enter admin');
    assert.equal(step.statements[1].intent, 'Click login');
  });

  it('wraps template without params (no template_params key)', () => {
    writeFileSync(join(templateTmpDir, 'templates', 'dismiss.yaml'), `
name: Dismiss
statements:
  - intent: Click dismiss
`);

    const doc = {
      goal: 'test',
      statements: [
        { template: './templates/dismiss.yaml' },
      ],
    };

    const sourceFile = join(templateTmpDir, 'test2.yaml');
    writeFileSync(sourceFile, '');
    const result = expandTemplates(doc, sourceFile);

    const step = result.doc.statements[0];
    assert.equal(step.STEP, 'Dismiss');
    assert.equal(step.template_path, './templates/dismiss.yaml');
    assert.equal(step.template_params, undefined, 'should not have template_params when no params provided');
  });

  it('tracks referenced template paths', () => {
    const doc = {
      goal: 'test',
      statements: [
        { template: './templates/login.yaml', params: { username: 'x' } },
      ],
    };

    const sourceFile = join(templateTmpDir, 'test3.yaml');
    writeFileSync(sourceFile, '');
    const result = expandTemplates(doc, sourceFile);

    assert.equal(result.referencedTemplatePaths.length, 1);
    assert.ok(result.referencedTemplatePaths[0].includes('login.yaml'));
  });
});

// ============================================================================
// parseYamlTestFile — template_path survives through to TestFlow
// ============================================================================

const parserTmpDir = join(tmpdir(), 'parse-template-test-' + Date.now());

describe('parseYamlTestFile template_path', () => {
  mkdirSync(join(parserTmpDir, 'templates'), { recursive: true });

  after(() => {
    rmSync(parserTmpDir, { recursive: true, force: true });
  });

  it('preserves template_path on Step statements after parsing', () => {
    writeFileSync(join(parserTmpDir, 'templates', 'login.yaml'), `
name: Login
params:
  - user
statements:
  - intent: Enter <<user>>
`);

    const yaml = `
goal: test
statements:
  - template: ./templates/login.yaml
    params:
      user: admin
  - intent: do something
`;

    const sourceFile = join(parserTmpDir, 'test.test.yaml');
    writeFileSync(sourceFile, yaml);
    const parsed = parseYamlTestFile(yaml, sourceFile);
    const stmts = parsed.testFlow!.statements!;

    // First statement should be a STEP with template_path
    const step = stmts[0] as Step;
    assert.equal(step.type, 'STEP');
    assert.equal(step.template_path, './templates/login.yaml');
    assert.deepEqual(step.template_params, { user: 'admin' });

    // Second statement should be a normal DRAFT
    assert.equal(stmts[1].type, 'DRAFT');
  });
});

/**
 * Regression tests for issue #2209 — a suite file's `base_url` never reached the
 * generated spec, so every relative `URL:` failed at runtime.
 *
 * `base_url` is documented in the YAML spec §3 as a TOP-LEVEL key that maps to
 * `test.use({ baseURL })`, with no suite exception. The suite parser only ever
 * read the undocumented nested `suite.base_url` (written by `suiteToYaml` on the
 * debugger round-trip), so the documented form was silently discarded.
 */
describe('suite base_url → test.use({ baseURL })', () => {
  const suiteTmpDir = join(tmpdir(), 'suite-baseurl-test-' + Date.now());
  mkdirSync(suiteTmpDir, { recursive: true });

  after(() => {
    rmSync(suiteTmpDir, { recursive: true, force: true });
  });

  const suiteBody = `
suite:
  beforeEach:
    - URL: /
  tests:
    - name: anything
      statements:
        - VERIFY: The page loaded
          js: "await expect(page).toHaveURL(/example/)"
`;

  function transpileSuite(fileName: string, yaml: string): string {
    const filePath = join(suiteTmpDir, fileName);
    writeFileSync(filePath, yaml);
    const result = transpileYamlContent(yaml, filePath, { version: '0.0.1-test' });
    assert.equal(result.valid, true, `transpile failed: ${result.errors.join(', ')}`);
    return readFileSync(result.specFile!, 'utf-8');
  }

  it('emits baseURL for a top-level base_url on a suite file', () => {
    const content = transpileSuite('top-level.test.yaml', `
name: Repro
base_url: https://example.com
${suiteBody}`);

    assert.match(content, /test\.use\(/);
    assert.match(content, /"baseURL": "https:\/\/example\.com"/);
  });

  it('still honors the nested suite.base_url written by suiteToYaml', () => {
    const content = transpileSuite('nested.test.yaml', `
name: Repro
suite:
  base_url: https://nested.example.com
  tests:
    - name: anything
      statements:
        - VERIFY: ok
          js: "await expect(page).toHaveURL(/example/)"
`);

    assert.match(content, /"baseURL": "https:\/\/nested\.example\.com"/);
  });

  it('merges base_url alongside other use: keys instead of replacing them', () => {
    const content = transpileSuite('with-use.test.yaml', `
name: Repro
base_url: https://example.com
use:
  extensionDir: ./dist
${suiteBody}`);

    assert.match(content, /"baseURL": "https:\/\/example\.com"/);
    assert.match(content, /"extensionDir": "\.\/dist"/);
  });

  it('lets base_url take precedence over use.baseURL, matching single-test files', () => {
    const content = transpileSuite('precedence.test.yaml', `
name: Repro
base_url: https://wins.example.com
use:
  baseURL: https://loses.example.com
${suiteBody}`);

    assert.match(content, /"baseURL": "https:\/\/wins\.example\.com"/);
    assert.doesNotMatch(content, /loses\.example\.com/);
  });

  it('emits no test.use block when a suite sets neither base_url nor use', () => {
    const content = transpileSuite('bare.test.yaml', `
name: Repro
${suiteBody}`);

    assert.doesNotMatch(content, /test\.use\(/);
  });
});

/**
 * Regression tests for the follow-up to issue #2209 — file-level
 * `test.use({ baseURL })` does NOT reach worker-scoped beforeAll/afterAll hooks.
 *
 * Those hooks build their own page from `workerInfo.project.use`, which
 * Playwright populates from playwright.config.ts only. A suite that sets
 * base_url and navigates relatively in beforeAll therefore kept failing with
 * `Invalid URL` even after base_url started reaching test.use().
 */
describe('suite base_url reaches worker-scoped hooks', () => {
  const hookTmpDir = join(tmpdir(), 'suite-hook-baseurl-' + Date.now());
  mkdirSync(hookTmpDir, { recursive: true });

  after(() => {
    rmSync(hookTmpDir, { recursive: true, force: true });
  });

  function transpileSuite(fileName: string, yaml: string): string {
    const filePath = join(hookTmpDir, fileName);
    writeFileSync(filePath, yaml);
    const result = transpileYamlContent(yaml, filePath, { version: '0.0.1-test' });
    assert.equal(result.valid, true, `transpile failed: ${result.errors.join(', ')}`);
    return readFileSync(result.specFile!, 'utf-8');
  }

  it('uses the file-level base_url for the beforeAll page, not just the project config', () => {
    const content = transpileSuite('hook-baseurl.test.yaml', `
name: Repro
base_url: https://example.com
suite:
  beforeAll:
    - URL: /login
  tests:
    - name: anything
      statements:
        - VERIFY: ok
          js: "await expect(page).toHaveURL(/example/)"
`);

    const hookLine = content.split('\n').find(l => l.includes('browser.newPage('))!;
    assert.ok(hookLine, 'beforeAll must create a page');
    assert.match(hookLine, /https:\/\/example\.com/, 'hook page must carry the file-level baseURL');
  });

  it('does the same for afterAll', () => {
    const content = transpileSuite('hook-baseurl-after.test.yaml', `
name: Repro
base_url: https://example.com
suite:
  afterAll:
    - URL: /logout
  tests:
    - name: anything
      statements:
        - VERIFY: ok
          js: "await expect(page).toHaveURL(/example/)"
`);

    const hookLine = content.split('\n').find(l => l.includes('browser.newPage('))!;
    assert.match(hookLine, /https:\/\/example\.com/);
  });

  it('falls back to the project config baseURL when the suite sets no base_url', () => {
    const content = transpileSuite('hook-no-baseurl.test.yaml', `
name: Repro
suite:
  beforeAll:
    - URL: https://example.com/login
  tests:
    - name: anything
      statements:
        - VERIFY: ok
          js: "await expect(page).toHaveURL(/example/)"
`);

    const hookLine = content.split('\n').find(l => l.includes('browser.newPage('))!;
    assert.match(hookLine, /workerInfo\.project\.use\.baseURL/);
  });

  it('honors a use.baseURL set without base_url', () => {
    const content = transpileSuite('hook-use-baseurl.test.yaml', `
name: Repro
use:
  baseURL: https://from-use.example.com
suite:
  beforeAll:
    - URL: /login
  tests:
    - name: anything
      statements:
        - VERIFY: ok
          js: "await expect(page).toHaveURL(/example/)"
`);

    const hookLine = content.split('\n').find(l => l.includes('browser.newPage('))!;
    assert.match(hookLine, /https:\/\/from-use\.example\.com/);
  });
});
