/**
 * YAML Test Transpiler
 *
 * Converts parsed YAML 1.3.0 TestFlow into Playwright test files
 * using the shiplightai fixture for agent injection.
 */

import type { TestFlow, Statement, Action, Step, IfElse, WhileLoop } from 'shiplight-types';
import { StatementType, yamlToTestFlow } from 'shiplight-types';
import { stringify as stringifyYaml } from 'yaml';
import { transpileStatements, type TranspileOptions } from './statements';
import { assignDeterministicUids } from './yamlParser';
import { escapeString } from './utils';
import type {
  ParsedSuite,
  TranspileFileOptions,
} from './types';

/* ================================================================
 * Single-test transpiler
 * ================================================================ */

/**
 * Transpile a TestFlow into a complete Playwright test file string
 */
export function transpileYamlTest(
  testFlow: TestFlow,
  options?: TranspileFileOptions,
): string {
  const lines: string[] = [];

  // Version header for cache invalidation
  const version = options?.version || 'unknown';
  lines.push(`// @generated by shiplightai v${version}`);

  // Generate imports
  lines.push(...generateImports());
  lines.push('');

  // Generate test.use() if provided
  if (options?.use && Object.keys(options.use).length > 0) {
    lines.push(`test.use(${JSON.stringify(options.use, null, 2)});`);
    lines.push('');
  }

  const collectedImports = new Set<string>();
  const transpileOptions: TranspileOptions = {
    imports: collectedImports,
    actionEntityStore: options?.actionEntityStore,
    onActionEntitySource: options?.onActionEntitySource,
    filePath: options?.filePath,
    yamlDir: options?.yamlDir,
    projectRoot: options?.projectRoot,
  };

  // Generate beforeEach hook (single-test)
  if (options?.beforeEach && options.beforeEach.length > 0) {
    lines.push(...transpileHookBlock('beforeEach', options.beforeEach, transpileOptions));
    lines.push('');
  }

  // Build execution control options
  const controlOptions: TestControlOptions | undefined =
    (options?.timeout || options?.skip !== undefined || options?.fail !== undefined || options?.only || options?.slow)
      ? { timeout: options.timeout, skip: options.skip, fail: options.fail, only: options.only, slow: options.slow }
      : undefined;

  // Handle parameterized tests
  const fileTags = normalizeTags(options?.tags);
  if (options?.parameters && options.parameters.length > 0) {
    const testName = options?.testName || testFlow.goal || 'Generated test';

    for (const paramSet of options.parameters) {
      lines.push(...transpileTestBody(
        testFlow,
        `${escapeString(testName)} [${escapeString(paramSet.name)}]`,
        transpileOptions,
        0,
        controlOptions,
        normalizeTags(fileTags, [paramSet.name]),
        paramSet.values,
      ));
      lines.push('');
    }
  } else {
    // Standard single test
    const testName = options?.testName || testFlow.goal || 'Generated test';
    lines.push(...transpileTestBody(
      testFlow,
      escapeString(testName),
      transpileOptions,
      0,
      controlOptions,
      fileTags,
    ));
  }

  // Generate afterEach hook (single-test)
  if (options?.afterEach && options.afterEach.length > 0) {
    lines.push('');
    lines.push(...transpileHookBlock('afterEach', options.afterEach, transpileOptions));
  }

  // Inject any imports collected during transpilation
  injectCollectedImports(lines, collectedImports);

  return lines.join('\n');
}

/* ================================================================
 * Suite transpiler
 * ================================================================ */

/**
 * Transpile a ParsedSuite into a Playwright test.describe() file
 */
export function transpileYamlSuite(
  suite: ParsedSuite,
  options?: TranspileFileOptions,
): string {
  const lines: string[] = [];

  // Version header
  const version = options?.version || 'unknown';
  lines.push(`// @generated by shiplightai v${version}`);

  // Generate imports
  lines.push(...generateImports());
  lines.push('');

  // Generate test.use() if provided (outside describe)
  if (options?.use && Object.keys(options.use).length > 0) {
    lines.push(`test.use(${JSON.stringify(options.use, null, 2)});`);
    lines.push('');
  }

  const collectedImports = new Set<string>();
  const baseURL = options?.use?.baseURL;
  const transpileOptions: TranspileOptions = {
    imports: collectedImports,
    actionEntityStore: options?.actionEntityStore,
    onActionEntitySource: options?.onActionEntitySource,
    filePath: options?.filePath,
    yamlDir: options?.yamlDir,
    projectRoot: options?.projectRoot,
    fileBaseURL: typeof baseURL === 'string' ? baseURL : undefined,
  };

  // Describe block
  const suiteName = options?.testName || 'Test Suite';
  const suiteTags = normalizeTags(options?.tags);
  const suiteTagOption = buildTagOption(suiteTags);
  // Suites always run sequentially — for parallel tests, use separate test files
  const describeMethod = 'test.describe.serial';

  lines.push(`${describeMethod}('${escapeString(suiteName)}'${suiteTagOption}, () => {`);

  // Suite-level hooks
  if (suite.beforeAll && suite.beforeAll.length > 0) {
    lines.push(...transpileSuiteHookBlock('beforeAll', suite.beforeAll, transpileOptions, 1));
    lines.push('');
  }

  if (suite.beforeEach && suite.beforeEach.length > 0) {
    lines.push(...transpileSuiteHookBlock('beforeEach', suite.beforeEach, transpileOptions, 1));
    lines.push('');
  }

  // Tests
  for (let i = 0; i < suite.tests.length; i++) {
    const suiteTest = suite.tests[i];

    // Build per-test execution control options
    const suiteControlOptions: TestControlOptions | undefined =
      (suiteTest.timeout || suiteTest.skip !== undefined || suiteTest.fail !== undefined || suiteTest.only || suiteTest.slow)
        ? { timeout: suiteTest.timeout, skip: suiteTest.skip, fail: suiteTest.fail, only: suiteTest.only, slow: suiteTest.slow }
        : undefined;

    // Tags for one test inside this suite. Suite-level tags are dropped rather
    // than repeated: Playwright already applies a describe's tags to every test
    // inside it, and re-declaring one makes it appear twice in `test.tags` and
    // in Playwright's own reporters. The subtraction has to happen *after* the
    // parameter-set name is merged in — a parameter set can share a name with a
    // suite tag, which is how the duplicate slipped back in once already.
    const tagsForSuiteTest = (...extra: (string[] | undefined)[]): string[] =>
      normalizeTags(suiteTest.tags, ...extra).filter((t) => !suiteTags.includes(t));

    if (suiteTest.parameters && suiteTest.parameters.length > 0) {
      // Parameterized suite test
      for (const paramSet of suiteTest.parameters) {
        lines.push(...transpileTestBody(
          suiteTest.testFlow,
          `${escapeString(suiteTest.name)} [${escapeString(paramSet.name)}]`,
          transpileOptions,
          1,
          suiteControlOptions,
          tagsForSuiteTest([paramSet.name]),
          paramSet.values,
        ));
        lines.push('');
      }
    } else {
      lines.push(...transpileTestBody(
        suiteTest.testFlow,
        escapeString(suiteTest.name),
        transpileOptions,
        1,
        suiteControlOptions,
        tagsForSuiteTest(),
      ));
      if (i < suite.tests.length - 1 || suite.afterEach || suite.afterAll) {
        lines.push('');
      }
    }
  }

  // Suite-level afterEach/afterAll
  if (suite.afterEach && suite.afterEach.length > 0) {
    lines.push(...transpileSuiteHookBlock('afterEach', suite.afterEach, transpileOptions, 1));
    lines.push('');
  }

  if (suite.afterAll && suite.afterAll.length > 0) {
    lines.push(...transpileSuiteHookBlock('afterAll', suite.afterAll, transpileOptions, 1));
  }

  lines.push('});');

  // Inject any imports collected during transpilation
  injectCollectedImports(lines, collectedImports);

  return lines.join('\n');
}

/* ================================================================
 * Shared helpers
 * ================================================================ */

/**
 * Flatten the given tag sources into one deduplicated list: drop blank entries
 * and strip a leading `@` the author may have written, so `tags: [smoke]` and
 * `tags: ['@smoke']` both yield the bare name `smoke`. Deduplication matters
 * because a parameter-set name may repeat a tag already declared on the file.
 *
 * Scalar entries are coerced rather than assumed to be strings: the parser casts
 * `tags` without checking the element type, so unquoted YAML scalars arrive as
 * numbers or booleans (`tags: [2026]` — a year, a version, a ticket number).
 * Those must keep transpiling, as they did when this built the tag by
 * interpolation; throwing here would surface as a bare `shiplight test`
 * silently skipping the whole file.
 *
 * Maps and sequences are dropped instead, because coercing them yields a tag
 * like `@[object Object]` that Playwright accepts and no `--grep` will ever
 * select — worse than absent, since it looks tagged.
 */
function normalizeTags(...groups: (string[] | undefined)[]): string[] {
  const seen = new Set(
    groups
      .flatMap((g) => g ?? [])
      .filter((t) => t === null || t === undefined || typeof t !== 'object')
      .map((t) => String(t ?? '').trim().replace(/^@+/, '').trim())
      .filter((t) => t.length > 0),
  );
  return Array.from(seen);
}

/**
 * Render normalized tag names as Playwright's `{ tag: [...] }` options argument,
 * or `''` when there are none.
 *
 * The options form is used rather than an in-title `@token` prefix (Playwright's
 * pre-1.42 convention) for three reasons: the reported title stays clean — the
 * reporter uploads `test.title` verbatim as the cloud test-case name and matches
 * suite tests back to their YAML by that title; multi-word tags survive, which
 * the title-token recognizer (`@\S+`) would truncate; and `--grep '@smoke'`
 * keeps working either way, since Playwright greps tags alongside the title.
 */
function buildTagOption(tags: string[]): string {
  return tags.length > 0
    ? `, { tag: [${tags.map((t) => `'@${escapeString(t)}'`).join(', ')}] }`
    : '';
}

interface TestControlOptions {
  timeout?: number;
  skip?: boolean | string;
  fail?: boolean | string;
  only?: boolean;
  slow?: boolean;
}

/**
 * Extra fixture params that need explicit destructuring when used in function call args.
 * `page` and `agent` are always destructured so they're excluded.
 */
const EXTRA_FIXTURE_PARAMS = ['testContext', 'request', 'extensionActionPopup'] as const;

/**
 * Add fixture names referenced as identifiers in executable JavaScript.
 */
function collectFixturesFromJavaScript(source: unknown, extras: Set<string>): void {
  if (typeof source !== 'string') return;

  for (const fixture of EXTRA_FIXTURE_PARAMS) {
    if (new RegExp(`\\b${fixture}\\b`).test(source)) {
      extras.add(fixture);
    }
  }
}

/**
 * Walk statements recursively and collect extra fixture names referenced
 * in function arguments or executable JavaScript.
 */
function collectExtraFixtures(statements: Statement[]): Set<string> {
  const extras = new Set<string>();

  function walk(stmts: Statement[]): void {
    for (const stmt of stmts) {
      switch (stmt.type) {
        case StatementType.ACTION: {
          const action = stmt as Action;
          const kwargs = action.action_entity?.action_data?.kwargs;
          const argSources = [
            ...(Array.isArray(kwargs?.args) ? kwargs.args : []),
            ...(Array.isArray(kwargs?.parameterValues) ? kwargs.parameterValues : []),
          ];
          for (const arg of argSources) {
            if (typeof arg === 'string' && (EXTRA_FIXTURE_PARAMS as readonly string[]).includes(arg)) {
              extras.add(arg);
            }
          }
          collectFixturesFromJavaScript(kwargs?.code, extras);
          collectFixturesFromJavaScript(kwargs?.js, extras);
          break;
        }
        case StatementType.STEP:
          walk((stmt as Step).statements);
          break;
        case StatementType.IF_ELSE: {
          const ifElse = stmt as IfElse;
          if (ifElse.condition.type === 'JS_CODE') {
            collectFixturesFromJavaScript(ifElse.condition.expression, extras);
          }
          walk(ifElse.then);
          if (ifElse.else) walk(ifElse.else);
          break;
        }
        case StatementType.WHILE_LOOP: {
          const whileLoop = stmt as WhileLoop;
          if (whileLoop.condition.type === 'JS_CODE') {
            collectFixturesFromJavaScript(whileLoop.condition.expression, extras);
          }
          walk(whileLoop.body);
          break;
        }
      }
    }
  }

  walk(statements);
  return extras;
}

/**
 * Collect extra fixtures from a TestFlow (statements + teardown).
 */
function collectExtraFixturesFromFlow(testFlow: TestFlow): Set<string> {
  const extras = collectExtraFixtures(testFlow.statements ?? []);
  if (testFlow.teardown) {
    for (const f of collectExtraFixtures(testFlow.teardown)) {
      extras.add(f);
    }
  }
  return extras;
}

/**
 * Build the fixture destructure string, e.g. `{ page, agent }` or `{ page, agent, testContext }`.
 */
function buildFixtureDestructure(extras: Set<string>): string {
  const params = ['page', 'agent', ...Array.from(extras).sort()];
  return `{ ${params.join(', ')} }`;
}

function transpileTestBody(
  testFlow: TestFlow,
  testTitle: string,
  transpileOptions: TranspileOptions,
  baseIndent: number = 0,
  controlOptions?: TestControlOptions,
  tags?: string[],
  paramValues?: Record<string, string>,
): string[] {
  const outerIndent = '  '.repeat(baseIndent);
  const lines: string[] = [];

  const extras = collectExtraFixturesFromFlow(testFlow);
  const fixtures = buildFixtureDestructure(extras);
  const testFn = controlOptions?.only ? 'test.only' : 'test';
  // YAML `tags:` and the parameter-set name both land here as Playwright tags,
  // so `--grep '@smoke'` and `--grep '@admin'` select without bracket escaping.
  const tagArg = buildTagOption(tags ?? []);
  lines.push(
    `${outerIndent}${testFn}('${testTitle}'${tagArg}, async (${fixtures}) => {`,
  );

  // Execution control annotations
  if (controlOptions?.skip === true) {
    lines.push(`${outerIndent}  test.skip();`);
  } else if (typeof controlOptions?.skip === 'string') {
    lines.push(`${outerIndent}  test.skip(true, '${escapeString(controlOptions.skip)}');`);
  }
  if (controlOptions?.fail === true) {
    lines.push(`${outerIndent}  test.fail();`);
  } else if (typeof controlOptions?.fail === 'string') {
    lines.push(`${outerIndent}  test.fail(true, '${escapeString(controlOptions.fail)}');`);
  }
  if (controlOptions?.slow) {
    lines.push(`${outerIndent}  test.slow();`);
  }
  if (controlOptions?.timeout) {
    lines.push(`${outerIndent}  test.setTimeout(${controlOptions.timeout});`);
  }

  // Set parameter values as runtime variables
  if (paramValues) {
    for (const [key, value] of Object.entries(paramValues)) {
      lines.push(`${outerIndent}  agent.agentServices.saveVariable(${JSON.stringify(key)}, ${JSON.stringify(value)});`);
    }
    lines.push('');
  }

  // Transpile main statements and teardown
  const hasTeardown = testFlow.teardown && testFlow.teardown.length > 0;
  const stmtIndent = baseIndent + 1;

  if (hasTeardown) {
    lines.push(`${outerIndent}  try {`);
    if (testFlow.statements && testFlow.statements.length > 0) {
      lines.push(`${outerIndent}    // Test steps`);
      const statementLines = transpileStatements(testFlow.statements, stmtIndent + 1, transpileOptions);
      lines.push(...statementLines);
    }
    lines.push(`${outerIndent}  } finally {`);
    lines.push(`${outerIndent}    // Teardown`);
    const teardownLines = transpileStatements(
      testFlow.teardown!,
      stmtIndent + 1,
      transpileOptions,
      'teardown',
    );
    lines.push(...teardownLines);
    lines.push(`${outerIndent}  }`);
  } else {
    if (testFlow.statements && testFlow.statements.length > 0) {
      lines.push(`${outerIndent}  // Test steps`);
      const statementLines = transpileStatements(testFlow.statements, stmtIndent, transpileOptions);
      lines.push(...statementLines);
    }
  }

  lines.push(`${outerIndent}});`);

  return lines;
}

function transpileHookBlock(
  hookName: 'beforeEach' | 'afterEach',
  rawStatements: any[],
  transpileOptions: TranspileOptions,
): string[] {
  const lines: string[] = [];
  const stmts = parseRawStatements(rawStatements, transpileOptions.filePath, hookName);

  const extras = collectExtraFixtures(stmts);
  const fixtures = buildFixtureDestructure(extras);
  lines.push(`test.${hookName}(async (${fixtures}) => {`);
  lines.push(...transpileStatements(stmts, 1, transpileOptions, hookName));
  lines.push('});');

  return lines;
}

function transpileSuiteHookBlock(
  hookName: 'beforeAll' | 'afterAll' | 'beforeEach' | 'afterEach',
  rawStatements: any[],
  transpileOptions: TranspileOptions,
  baseIndent: number,
): string[] {
  const indent = '  '.repeat(baseIndent);
  const lines: string[] = [];
  const stmts = parseRawStatements(rawStatements, transpileOptions.filePath, hookName);

  const isWorkerScoped = hookName === 'beforeAll' || hookName === 'afterAll';

  if (isWorkerScoped) {
    const noAgentOptions = { ...transpileOptions, noAgent: true };
    // The file's own baseURL wins, mirroring how test.use() overrides the
    // project config for the tests themselves. Without this the hook page falls
    // back to workerInfo.project.use.baseURL, which never reflects a file-level
    // test.use() — see TranspileOptions.fileBaseURL and issue #2209.
    const hookBaseURL = transpileOptions.fileBaseURL !== undefined
      ? JSON.stringify(transpileOptions.fileBaseURL)
      : 'workerInfo.project.use.baseURL';
    lines.push(`${indent}test.${hookName}(async ({ browser }, workerInfo) => {`);
    lines.push(`${indent}  const page = await browser.newPage({ baseURL: ${hookBaseURL} });`);
    lines.push(...transpileStatements(stmts, baseIndent + 1, noAgentOptions, hookName));
    lines.push(`${indent}  await page.close();`);
    lines.push(`${indent}});`);
  } else {
    const extras = collectExtraFixtures(stmts);
    const fixtures = buildFixtureDestructure(extras);
    lines.push(`${indent}test.${hookName}(async (${fixtures}) => {`);
    lines.push(...transpileStatements(stmts, baseIndent + 1, transpileOptions, hookName));
    lines.push(`${indent}});`);
  }

  return lines;
}

/**
 * Parse a hook's raw statement list.
 *
 * `yamlToTestFlow` stamps a fresh `uuidv4()` on every statement, so without the
 * deterministic re-keying below a hook's UIDs differ on every transpile. That
 * makes hook actions permanently uncacheable — the store lookup in
 * `transpileAction` can never match — and worse, a heal inside a hook is written
 * back to the cache under a UUID that will never be generated again, so the
 * cache grows dead entries forever. The prefix is the hook name, keeping this
 * namespace disjoint from the `main`/`teardown` UIDs `parseYamlTestFile`
 * assigns; the file path is the same absolute path used there, so hooks key the
 * same way the rest of the file does.
 */
function parseRawStatements(
  rawStatements: any[],
  filePath: string | undefined,
  pathPrefix: string,
): Statement[] {
  const miniDoc = {
    goal: '_hook',
    statements: rawStatements,
  };
  const yaml = stringifyYaml(miniDoc);
  const flow = yamlToTestFlow(yaml);
  const stmts = flow.statements ?? [];
  if (filePath) assignDeterministicUids(stmts, filePath, pathPrefix);
  return stmts;
}

function generateImports(): string[] {
  return [
    "import { test, expect } from 'shiplightai/fixture';",
  ];
}

function injectCollectedImports(lines: string[], collectedImports: Set<string>): void {
  if (collectedImports.size > 0) {
    let insertIdx = 0;
    for (let i = 0; i < lines.length; i++) {
      if (lines[i].startsWith('import ')) {
        insertIdx = i + 1;
      }
    }
    const importLines = Array.from(collectedImports);
    lines.splice(insertIdx, 0, ...importLines);
  }
}
