/**
 * Extension Relay Server
 * Follows OpenClaw architecture:
 * - Single /cdp endpoint (not /cdp/{sessionId})
 * - SessionIds come from extension (not generated by relay)
 * - Global connectedTargets map
 */

import http, { IncomingMessage } from 'node:http';
import WebSocket, { WebSocketServer } from 'ws';

const logger = {
  info: (...args: any[]) => console.log('[ExtensionRelayServer]', ...args),
  warn: (...args: any[]) => console.warn('[ExtensionRelayServer]', ...args),
  error: (...args: any[]) => console.error('[ExtensionRelayServer]', ...args),
};

// CDP Types (from OpenClaw)
type CdpCommand = {
  id: number;
  method: string;
  params?: unknown;
  sessionId?: string;
};

type CdpResponse = {
  id: number;
  result?: unknown;
  error?: { message: string };
  sessionId?: string;
};

type CdpEvent = {
  method: string;
  params?: unknown;
  sessionId?: string;
};

// Extension Message Types
type ExtensionForwardCommandMessage = {
  id: number;
  method: 'forwardCDPCommand';
  params: { method: string; params?: unknown; sessionId?: string };
};

type ExtensionDetachTabMessage = {
  id: number;
  method: 'detachTab';
  params: { sessionId: string };
};

type ExtensionCommandMessage = ExtensionForwardCommandMessage | ExtensionDetachTabMessage;

type ExtensionResponseMessage = {
  id: number;
  result?: unknown;
  error?: string;
};

type ExtensionForwardEventMessage = {
  method: 'forwardCDPEvent';
  params: { method: string; params?: unknown; sessionId?: string };
};

type ExtensionPingMessage = { method: 'ping' };
type ExtensionPongMessage = { method: 'pong' };

type ExtensionMessage =
  | ExtensionResponseMessage
  | ExtensionForwardEventMessage
  | ExtensionPongMessage;

// Target Types
type TargetInfo = {
  targetId: string;
  type?: string;
  title?: string;
  url?: string;
  attached?: boolean;
  browserContextId?: string;
};

/** Fixed browser context ID — Playwright requires this in targetInfo */
const RELAY_BROWSER_CONTEXT_ID = 'relay-default-context';

type AttachedToTargetEvent = {
  sessionId: string;
  targetInfo: TargetInfo;
  waitingForDebugger?: boolean;
};

type DetachedFromTargetEvent = {
  sessionId: string;
  targetId?: string;
};

type ConnectedTarget = {
  sessionId: string;
  targetId: string;
  targetInfo: TargetInfo;
};

export class ExtensionRelayServer {
  private httpServer: http.Server | null = null;
  private wssExtension: WebSocketServer | null = null;
  private wssCdp: WebSocketServer | null = null;

  private port: number = 0;

  // Extension connection (single connection)
  private extensionWs: WebSocket | null = null;

  // CDP clients (multiple Playwright connections)
  private cdpClients = new Set<WebSocket>();

  // Connected targets (tabs attached by extension)
  private connectedTargets = new Map<string, ConnectedTarget>();

  // Pending extension requests
  private pendingExtensionRequests = new Map<
    number,
    {
      resolve: (value: unknown) => void;
      reject: (error: Error) => void;
      timer: NodeJS.Timeout;
    }
  >();
  private nextExtensionId = 1;

  /**
   * Start the relay server
   */
  async start(port: number): Promise<void> {
    this.port = port;

    // Create HTTP server with CDP-compatible endpoints
    this.httpServer = http.createServer((req, res) => {
      // Set CORS headers
      res.setHeader('Access-Control-Allow-Origin', '*');
      res.setHeader('Access-Control-Allow-Methods', 'GET, HEAD, OPTIONS');
      res.setHeader('Access-Control-Allow-Headers', 'Content-Type');

      if (req.method === 'OPTIONS') {
        res.writeHead(204);
        res.end();
        return;
      }

      const url = new URL(req.url || '/', `http://${req.headers.host}`);
      // Normalize: strip trailing slash (Playwright requests /json/version/)
      const pathname = url.pathname.replace(/\/+$/, '') || '/';

      // CDP /json/version endpoint
      if (pathname === '/json/version' || pathname === '/json') {
        res.writeHead(200, { 'Content-Type': 'application/json' });
        res.end(
          JSON.stringify({
            Browser: 'Chrome/Shiplight-Extension-Relay',
            'Protocol-Version': '1.3',
            'User-Agent': 'Shiplight/1.0',
            'V8-Version': '0.0.0',
            'WebKit-Version': '0.0.0',
            webSocketDebuggerUrl: `ws://127.0.0.1:${port}/cdp`,
          })
        );
        return;
      }

      // CDP /json/list endpoint
      if (pathname === '/json/list') {
        const targets = Array.from(this.connectedTargets.values()).map((target) => ({
          id: target.targetId,
          type: 'page',
          title: target.targetInfo.title,
          url: target.targetInfo.url,
          devtoolsFrontendUrl: `devtools://devtools/bundled/inspector.html?ws=127.0.0.1:${port}/cdp`,
          webSocketDebuggerUrl: `ws://127.0.0.1:${port}/cdp`,
        }));
        res.writeHead(200, { 'Content-Type': 'application/json' });
        res.end(JSON.stringify(targets));
        return;
      }

      // Root endpoint
      if (pathname === '/' && (req.method === 'GET' || req.method === 'HEAD')) {
        res.writeHead(200, { 'Content-Type': 'application/json' });
        res.end(
          JSON.stringify({
            Browser: 'Chrome/Shiplight-Extension-Relay',
            'Protocol-Version': '1.3',
            'User-Agent': 'Shiplight/1.0',
            'V8-Version': '0.0.0',
            'WebKit-Version': '0.0.0',
            webSocketDebuggerUrl: `ws://127.0.0.1:${port}/cdp`,
          })
        );
        return;
      }

      res.writeHead(404);
      res.end('Not Found');
    });

    // Create WebSocket servers
    this.wssExtension = new WebSocketServer({ noServer: true });
    this.wssCdp = new WebSocketServer({ noServer: true });

    // Setup upgrade handler
    this.setupUpgradeHandler();

    // Setup connection handlers
    this.setupExtensionConnectionHandler();
    this.setupCdpConnectionHandler();

    // Start HTTP server
    await new Promise<void>((resolve, reject) => {
      this.httpServer!.listen(port, '127.0.0.1', () => {
        logger.info(`Started on port ${port}`);
        resolve();
      });
      this.httpServer!.once('error', reject);
    });
  }

  /**
   * Stop the relay server
   */
  async stop(): Promise<void> {
    // Close extension connection
    if (this.extensionWs) {
      this.extensionWs.close();
      this.extensionWs = null;
    }

    // Close CDP clients
    for (const ws of this.cdpClients) {
      ws.close();
    }
    this.cdpClients.clear();

    // Close WebSocket servers
    if (this.wssExtension) {
      this.wssExtension.close();
      this.wssExtension = null;
    }
    if (this.wssCdp) {
      this.wssCdp.close();
      this.wssCdp = null;
    }

    // Close HTTP server
    if (this.httpServer) {
      await new Promise<void>((resolve) => {
        this.httpServer!.close(() => resolve());
      });
      this.httpServer = null;
    }

    logger.info('Stopped');
  }

  /**
   * Get list of connected tabs
   */
  getConnectedTabs(): Array<{ sessionId: string; targetId: string; url: string; title: string }> {
    return Array.from(this.connectedTargets.values()).map((target) => ({
      sessionId: target.sessionId,
      targetId: target.targetId,
      url: target.targetInfo.url || '',
      title: target.targetInfo.title || '',
    }));
  }

  /**
   * Get CDP WebSocket URL (single endpoint for all connections)
   */
  getCdpUrl(): string {
    return `ws://127.0.0.1:${this.port}/cdp`;
  }

  /**
   * Get CDP proxy URL for a specific session
   * Note: Single CDP endpoint, so sessionId is ignored
   */
  getCdpProxyUrl(_sessionId: string): string {
    return this.getCdpUrl();
  }

  /**
   * Get the relay server port
   */
  getPort(): number {
    return this.port;
  }

  /**
   * Get count of connected tabs
   */
  getConnectedTabsCount(): number {
    return this.connectedTargets.size;
  }

  /**
   * Wait for extension to attach to a tab
   * Returns when the first tab attachment is detected
   */
  /**
   * Ask extension for the currently active tab (OpenClaw pattern)
   */
  private async getActiveTabFromExtension(): Promise<string | null> {
    if (!this.extensionWs || this.extensionWs.readyState !== WebSocket.OPEN) {
      return null;
    }

    return new Promise((resolve) => {
      const id = Math.floor(Math.random() * 1000000);
      const timer = setTimeout(() => {
        resolve(null);
      }, 2000);

      const handler = (data: WebSocket.RawData) => {
        try {
          const msg = JSON.parse(data.toString());
          if (msg.id === id) {
            clearTimeout(timer);
            this.extensionWs!.off('message', handler);
            resolve(msg.result?.sessionId || null);
          }
        } catch {
          // Ignore parse errors
        }
      };

      const ws = this.extensionWs!;
      ws.on('message', handler);
      ws.send(JSON.stringify({ id, method: 'getActiveTab' }));
    });
  }

  async waitForAttachment(timeoutMs: number): Promise<{
    sessionId: string;
    tabInfo: { tabId: number; targetId: string; url: string; title: string };
  }> {
    // Helper to get tab by sessionId
    const getTabBySessionId = (sessionId: string) => {
      return this.connectedTargets.get(sessionId);
    };

    // First, try to get the active tab from extension (OpenClaw pattern)
    const activeSessionId = await this.getActiveTabFromExtension();
    if (activeSessionId) {
      const activeTab = getTabBySessionId(activeSessionId);
      if (activeTab) {
        const tabId = (activeTab.targetInfo as any).tabId || 0;
        return {
          sessionId: activeTab.sessionId,
          tabInfo: {
            tabId: typeof tabId === 'number' ? tabId : parseInt(String(tabId), 10) || 0,
            targetId: activeTab.targetId,
            url: activeTab.targetInfo.url || '',
            title: activeTab.targetInfo.title || '',
          },
        };
      }
    }

    // Fallback: if we have any connected tab, use the first one
    const existingTab = Array.from(this.connectedTargets.values())[0];
    if (existingTab) {
      const tabId = (existingTab.targetInfo as any).tabId || 0;
      return {
        sessionId: existingTab.sessionId,
        tabInfo: {
          tabId: typeof tabId === 'number' ? tabId : parseInt(String(tabId), 10) || 0,
          targetId: existingTab.targetId,
          url: existingTab.targetInfo.url || '',
          title: existingTab.targetInfo.title || '',
        },
      };
    }

    // Wait for a tab to be attached
    return new Promise((resolve, reject) => {
      const timer = setTimeout(() => {
        reject(new Error(`Timeout waiting for extension to attach to tab (${timeoutMs}ms)`));
      }, timeoutMs);

      // Poll for connected targets every 100ms
      const pollInterval = setInterval(async () => {
        // Try active tab first
        const activeSessionId = await this.getActiveTabFromExtension();
        if (activeSessionId) {
          const activeTab = getTabBySessionId(activeSessionId);
          if (activeTab) {
            clearTimeout(timer);
            clearInterval(pollInterval);
            const tabId = (activeTab.targetInfo as any).tabId || 0;
            resolve({
              sessionId: activeTab.sessionId,
              tabInfo: {
                tabId: typeof tabId === 'number' ? tabId : parseInt(String(tabId), 10) || 0,
                targetId: activeTab.targetId,
                url: activeTab.targetInfo.url || '',
                title: activeTab.targetInfo.title || '',
              },
            });
            return;
          }
        }

        // Fallback to any tab
        const anyTab = Array.from(this.connectedTargets.values())[0];
        if (anyTab) {
          clearTimeout(timer);
          clearInterval(pollInterval);
          const tabId = (anyTab.targetInfo as any).tabId || 0;
          resolve({
            sessionId: anyTab.sessionId,
            tabInfo: {
              tabId: typeof tabId === 'number' ? tabId : parseInt(String(tabId), 10) || 0,
              targetId: anyTab.targetId,
              url: anyTab.targetInfo.url || '',
              title: anyTab.targetInfo.title || '',
            },
          });
        }
      }, 100);
    });
  }

  /**
   * Clear all connected targets and broadcast targetDestroyed to CDP clients.
   * Called when the extension disconnects — all tabs become stale.
   */
  private clearAllTargets(): void {
    for (const target of this.connectedTargets.values()) {
      // Send detachedFromTarget (Playwright uses this to close Pages)
      this.broadcastToCdpClients({
        method: 'Target.detachedFromTarget',
        params: { sessionId: target.sessionId, targetId: target.targetId },
      });
      this.broadcastToCdpClients({
        method: 'Target.targetDestroyed',
        params: { targetId: target.targetId },
      });
    }
    const count = this.connectedTargets.size;
    this.connectedTargets.clear();
    if (count > 0) {
      logger.info(`Cleared ${count} stale target(s) after extension disconnect`);
    }
  }

  /**
   * Get the three-way mapping: Playwright targetId ↔ extension sessionId ↔ Chrome tabId
   */
  getTabMapping(): Array<{ sessionId: string; targetId: string; tabId: number; url: string; title: string }> {
    return Array.from(this.connectedTargets.values()).map((target) => ({
      sessionId: target.sessionId,
      targetId: target.targetId,
      tabId: (target.targetInfo as any).tabId || 0,
      url: target.targetInfo.url || '',
      title: target.targetInfo.title || '',
    }));
  }

  /**
   * Clean up relay state for a detached MCP session.
   * NOTE: This does NOT tell the extension to detach the debugger.
   * The extension stays attached until the user clicks the icon.
   */
  async detachTab(sessionId: string): Promise<void> {
    const target = this.connectedTargets.get(sessionId);
    if (!target) {
      logger.warn(`[detachTab] Session ${sessionId} not found`);
      return;
    }

    // Remove from connected targets (just cleanup, don't notify extension)
    this.connectedTargets.delete(sessionId);

    // Broadcast targetDestroyed to CDP clients
    this.broadcastToCdpClients({
      method: 'Target.targetDestroyed',
      params: { targetId: target.targetId },
    });

    logger.info(`[detachTab] Cleaned up relay state for session ${sessionId}`);
    logger.info(`[detachTab] Extension debugger remains attached - user-controlled`);
  }

  /**
   * Setup WebSocket upgrade handler
   */
  private setupUpgradeHandler(): void {
    this.httpServer!.on('upgrade', (req, socket, head) => {
      const url = new URL(req.url || '', `http://${req.headers.host}`);

      // Handle extension WebSocket connections (localhost-only, no auth needed)
      if (url.pathname === '/extension') {
        this.wssExtension!.handleUpgrade(req, socket, head, (ws) => {
          this.wssExtension!.emit('connection', ws, req);
        });
        return;
      }

      // Handle CDP WebSocket connections (single /cdp endpoint)
      if (url.pathname === '/cdp') {
        this.wssCdp!.handleUpgrade(req, socket, head, (ws) => {
          this.wssCdp!.emit('connection', ws, req);
        });
        return;
      }

      // Unknown path
      socket.write('HTTP/1.1 404 Not Found\r\n\r\n');
      socket.destroy();
    });
  }

  /**
   * Setup extension connection handler
   */
  private setupExtensionConnectionHandler(): void {
    this.wssExtension!.on('connection', (ws: WebSocket) => {
      logger.info('Extension connected');
      this.extensionWs = ws;

      // Ping every 5 seconds
      const pingInterval = setInterval(() => {
        if (ws.readyState === WebSocket.OPEN) {
          ws.send(JSON.stringify({ method: 'ping' } as ExtensionPingMessage));
        }
      }, 5000);

      ws.on('message', (data) => {
        try {
          const msg: ExtensionMessage = JSON.parse(data.toString());
          this.handleExtensionMessage(msg);
        } catch (err) {
          logger.error('Failed to parse extension message:', err);
        }
      });

      ws.on('close', () => {
        logger.info('Extension disconnected');
        clearInterval(pingInterval);
        if (this.extensionWs === ws) {
          this.extensionWs = null;
          // Clear all targets — extension is gone, all tabs are stale
          this.clearAllTargets();
        }
      });

      ws.on('error', (err) => {
        logger.error('Extension WebSocket error:', err);
      });
    });
  }

  /**
   * Handle message from extension
   */
  private handleExtensionMessage(msg: ExtensionMessage): void {
    // Handle responses to forwardCDPCommand
    if ('id' in msg && typeof msg.id === 'number') {
      const pending = this.pendingExtensionRequests.get(msg.id);
      if (pending) {
        clearTimeout(pending.timer);
        this.pendingExtensionRequests.delete(msg.id);

        if ('error' in msg && typeof msg.error === 'string' && msg.error.trim()) {
          pending.reject(new Error(msg.error));
        } else {
          pending.resolve(msg.result);
        }
      }
      return;
    }

    // Handle forwardCDPEvent
    if ('method' in msg) {
      if (msg.method === 'pong') {
        return; // Ignore pong messages
      }

      if (msg.method === 'forwardCDPEvent') {
        const evt = msg as ExtensionForwardEventMessage;
        this.handleExtensionEvent(evt);
        return;
      }
    }
  }

  /**
   * Handle CDP event from extension
   */
  private handleExtensionEvent(evt: ExtensionForwardEventMessage): void {
    const method = evt.params?.method;
    const params = evt.params?.params;

    if (!method || typeof method !== 'string') {
      return;
    }

    // Handle Target.attachedToTarget event
    if (method === 'Target.attachedToTarget') {
      const attached = params as AttachedToTargetEvent;
      const targetType = attached?.targetInfo?.type ?? 'page';

      if (targetType !== 'page') {
        return;
      }

      if (attached?.sessionId && attached?.targetInfo?.targetId) {
        const prev = this.connectedTargets.get(attached.sessionId);
        const nextTargetId = attached.targetInfo.targetId;
        const prevTargetId = prev?.targetId;
        const isReannounce = prev && prevTargetId === nextTargetId;
        const changedTarget = prev && prevTargetId && prevTargetId !== nextTargetId;

        this.connectedTargets.set(attached.sessionId, {
          sessionId: attached.sessionId,
          targetId: nextTargetId,
          targetInfo: { ...attached.targetInfo, browserContextId: RELAY_BROWSER_CONTEXT_ID },
        });

        const storedTarget = this.connectedTargets.get(attached.sessionId)!;

        // Re-announce (same sessionId + same targetId, e.g. after navigation):
        // Just update target info — do NOT re-broadcast targetCreated/attachedToTarget
        // or Playwright will crash with "Duplicate target".
        if (isReannounce) {
          logger.info(`Tab re-announced: ${attached.sessionId} (targetId: ${nextTargetId})`);
          this.broadcastToCdpClients({
            method: 'Target.targetInfoChanged',
            params: { targetInfo: { ...storedTarget.targetInfo, attached: true } },
          });
          return;
        }

        logger.info(`Tab attached: ${attached.sessionId} (targetId: ${nextTargetId})`);

        if (changedTarget && prevTargetId) {
          // Broadcast targetDestroyed for old target
          this.broadcastToCdpClients({
            method: 'Target.targetDestroyed',
            params: { targetId: prevTargetId },
          });
        }

        // Broadcast targetCreated + attachedToTarget for new target
        // Both events are needed: targetCreated tells Playwright a target exists,
        // attachedToTarget (with sessionId) tells it the target is auto-attached
        // and triggers Page creation + context.on('page') event.
        this.broadcastToCdpClients({
          method: 'Target.targetCreated',
          params: { targetInfo: { ...storedTarget.targetInfo, attached: true } },
        });
        this.broadcastToCdpClients({
          method: 'Target.attachedToTarget',
          params: {
            sessionId: attached.sessionId,
            targetInfo: { ...storedTarget.targetInfo, attached: true },
            waitingForDebugger: false,
          },
        });
      }
      return;
    }

    // Handle Target.detachedFromTarget event
    if (method === 'Target.detachedFromTarget') {
      const detached = params as DetachedFromTargetEvent;
      if (detached?.sessionId) {
        const target = this.connectedTargets.get(detached.sessionId);
        this.connectedTargets.delete(detached.sessionId);

        logger.info(`Tab detached: ${detached.sessionId}`);

        if (target) {
          // Send detachedFromTarget (Playwright uses this to close Pages)
          this.broadcastToCdpClients({
            method: 'Target.detachedFromTarget',
            params: { sessionId: detached.sessionId, targetId: target.targetId },
          });
          this.broadcastToCdpClients({
            method: 'Target.targetDestroyed',
            params: { targetId: target.targetId },
          });
        }
      }
      return;
    }

    // Handle Target.targetInfoChanged event
    if (method === 'Target.targetInfoChanged') {
      const changed = params as { targetInfo?: TargetInfo };
      const targetInfo = changed?.targetInfo;
      const targetId = targetInfo?.targetId;

      if (targetId && (targetInfo?.type ?? 'page') === 'page') {
        for (const [sessionId, target] of this.connectedTargets) {
          if (target.targetId !== targetId) {
            continue;
          }
          this.connectedTargets.set(sessionId, {
            ...target,
            targetInfo: { ...target.targetInfo, ...targetInfo },
          });
        }

        // Broadcast to CDP clients
        this.broadcastToCdpClients({
          method: 'Target.targetInfoChanged',
          params: { targetInfo },
        });
      }
      return;
    }

    // For all other events, broadcast to CDP clients
    this.broadcastToCdpClients({
      method,
      params,
      sessionId: evt.params?.sessionId,
    });
  }

  /**
   * Setup CDP connection handler
   */
  private setupCdpConnectionHandler(): void {
    this.wssCdp!.on('connection', (ws: WebSocket) => {
      logger.info('CDP client connected');
      this.cdpClients.add(ws);

      ws.on('message', async (data) => {
        try {
          const cmd: CdpCommand = JSON.parse(data.toString());

          if (typeof cmd.id !== 'number' || typeof cmd.method !== 'string') {
            return;
          }

          logger.info(`[CDP → Relay] ${cmd.method} (id: ${cmd.id})`);

          // Route the command
          try {
            const result = await this.routeCdpCommand(cmd);

            // Send response
            this.sendResponseToCdp(ws, { id: cmd.id, sessionId: cmd.sessionId, result });

            // Post-command actions (from OpenClaw pattern)
            if (cmd.method === 'Target.setAutoAttach' && !cmd.sessionId) {
              this.ensureTargetEventsForClient(ws, 'autoAttach');
            }

            if (cmd.method === 'Target.setDiscoverTargets') {
              const params = (cmd.params ?? {}) as { discover?: boolean };
              if (params.discover === true) {
                this.ensureTargetEventsForClient(ws, 'discover');
              }
            }

            if (cmd.method === 'Target.attachToTarget') {
              const params = (cmd.params ?? {}) as { targetId?: string };
              const targetId = params.targetId;
              if (targetId) {
                const target = Array.from(this.connectedTargets.values()).find(
                  (t) => t.targetId === targetId
                );
                if (target) {
                  ws.send(
                    JSON.stringify({
                      method: 'Target.attachedToTarget',
                      params: {
                        sessionId: target.sessionId,
                        targetInfo: { ...target.targetInfo, attached: true },
                        waitingForDebugger: false,
                      },
                    } as CdpEvent)
                  );
                }
              }
            }
          } catch (err) {
            this.sendResponseToCdp(ws, {
              id: cmd.id,
              sessionId: cmd.sessionId,
              error: { message: err instanceof Error ? err.message : String(err) },
            });
          }
        } catch (err) {
          logger.error('Failed to parse CDP message:', err);
        }
      });

      ws.on('close', () => {
        logger.info('CDP client disconnected');
        this.cdpClients.delete(ws);
      });

      ws.on('error', (err) => {
        logger.error('CDP WebSocket error:', err);
      });
    });
  }

  /**
   * Route CDP command (from OpenClaw pattern)
   */
  private async routeCdpCommand(cmd: CdpCommand): Promise<unknown> {
    switch (cmd.method) {
      case 'Browser.getVersion':
        return {
          protocolVersion: '1.3',
          product: 'Chrome/Shiplight-Extension-Relay',
          revision: '0',
          userAgent: 'Shiplight/1.0',
          jsVersion: 'V8',
        };

      case 'Browser.setDownloadBehavior':
        return {};

      case 'Target.setAutoAttach':
      case 'Target.setDiscoverTargets':
        return {};

      case 'Target.getTargets':
        return {
          targetInfos: Array.from(this.connectedTargets.values()).map((t) => ({
            ...t.targetInfo,
            attached: true,
          })),
        };

      case 'Target.getTargetInfo': {
        const params = (cmd.params ?? {}) as { targetId?: string };
        const targetId = params.targetId;

        if (targetId) {
          for (const t of this.connectedTargets.values()) {
            if (t.targetId === targetId) {
              return { targetInfo: t.targetInfo };
            }
          }
        }

        if (cmd.sessionId && this.connectedTargets.has(cmd.sessionId)) {
          const t = this.connectedTargets.get(cmd.sessionId);
          if (t) {
            return { targetInfo: t.targetInfo };
          }
        }

        const first = Array.from(this.connectedTargets.values())[0];
        return { targetInfo: first?.targetInfo };
      }

      case 'Target.attachToTarget': {
        const params = (cmd.params ?? {}) as { targetId?: string };
        const targetId = params.targetId;

        if (!targetId) {
          throw new Error('targetId required');
        }

        for (const t of this.connectedTargets.values()) {
          if (t.targetId === targetId) {
            // Return EXISTING sessionId (not generating new one)
            return { sessionId: t.sessionId };
          }
        }

        throw new Error('target not found');
      }

      default: {
        // Forward to extension
        const id = this.nextExtensionId++;
        return await this.sendToExtension({
          id,
          method: 'forwardCDPCommand',
          params: {
            method: cmd.method,
            params: cmd.params,
            sessionId: cmd.sessionId,
          },
        });
      }
    }
  }

  /**
   * Send command to extension and wait for response
   */
  private async sendToExtension(payload: ExtensionCommandMessage): Promise<unknown> {
    if (!this.extensionWs || this.extensionWs.readyState !== WebSocket.OPEN) {
      throw new Error('Extension not connected');
    }

    this.extensionWs.send(JSON.stringify(payload));

    return await new Promise<unknown>((resolve, reject) => {
      const timer = setTimeout(() => {
        this.pendingExtensionRequests.delete(payload.id);
        const methodName = payload.method === 'forwardCDPCommand' ? payload.params.method : payload.method;
        reject(new Error(`Extension request timeout: ${methodName}`));
      }, 30_000);

      this.pendingExtensionRequests.set(payload.id, { resolve, reject, timer });
    });
  }

  /**
   * Send response to CDP client
   */
  private sendResponseToCdp(ws: WebSocket, response: CdpResponse): void {
    if (ws.readyState === WebSocket.OPEN) {
      ws.send(JSON.stringify(response));
    }
  }

  /**
   * Broadcast event to all CDP clients
   */
  private broadcastToCdpClients(event: CdpEvent): void {
    const msg = JSON.stringify(event);
    for (const ws of this.cdpClients) {
      if (ws.readyState === WebSocket.OPEN) {
        ws.send(msg);
      }
    }
  }

  /**
   * Send target events to specific CDP client (from OpenClaw pattern)
   */
  private ensureTargetEventsForClient(ws: WebSocket, mode: 'autoAttach' | 'discover'): void {
    for (const target of this.connectedTargets.values()) {
      if (mode === 'autoAttach') {
        ws.send(
          JSON.stringify({
            method: 'Target.attachedToTarget',
            params: {
              sessionId: target.sessionId,
              targetInfo: { ...target.targetInfo, attached: true },
              waitingForDebugger: false,
            },
          } as CdpEvent)
        );
      } else {
        ws.send(
          JSON.stringify({
            method: 'Target.targetCreated',
            params: { targetInfo: { ...target.targetInfo, attached: true } },
          } as CdpEvent)
        );
      }
    }
  }
}
