import { yamlToTestFlow } from './yamlFlowParser';
import { getAllStatementsInOrder } from './statementTreeWalker';
import { StatementType, ConditionType, type Action, type IfElse, type WhileLoop, type Statement } from './testFlow';

export interface ValidationStats {
  total: number;
  action: number;
  draft: number;
  coverage: number;
}

export interface ValidationResult {
  valid: boolean;
  errors: string[];
  warnings: string[];
  stats: ValidationStats;
}

/**
 * Minimum fraction of intent-based statements that must be enriched with an
 * `action:`/`js:` cache for a test to be considered replay-ready.
 *
 * This is the single definition of the rule. Callers differ only in the
 * VERDICT they draw from it — `shiplight transpile` warns, `--strict` fails —
 * never in the threshold or in how coverage is computed. A human and an agent
 * must not be able to get contradictory answers about the same file.
 */
export const DEFAULT_COVERAGE_THRESHOLD = 0.5;

/**
 * Does this file fall short of the action-coverage rule?
 *
 * Derived from the same `stats` the validator produced, so it cannot disagree
 * with the warning text. Callers use this to decide a verdict rather than
 * inferring one from `warnings.length` — that heuristic silently mislabels any
 * future non-coverage warning as a coverage failure.
 */
export function isBelowCoverageThreshold(
  stats: ValidationStats | undefined,
  threshold: number = DEFAULT_COVERAGE_THRESHOLD,
): boolean {
  if (!stats || stats.total === 0) return false;
  return stats.coverage / 100 < threshold;
}

// JS cache complexity cap: `verify js:` is a cache for a single natural-language
// assertion, not freeform code. If the cache grows past these limits, the upstream
// intent was too broad and should be split into multiple statements. The
// `description: + js:` escape hatch (js_code) is exempt — that's freeform code.
const MAX_JS_CACHE_LINES = 5;
const MAX_JS_CACHE_AWAITS = 3;

/**
 * Action names generated by YAML shorthands (no `intent:` field).
 * These are excluded from coverage counting.
 */
export const NON_INTENT_ACTIONS = new Set([
  'verify', 'ai_assert', 'done',
  'go_to_url', 'ai_wait_until', 'wait', 'js_code',
]);

/**
 * Count intent-based statements in a flattened statement list.
 * - DRAFT: bare `intent:` without action — needs enrichment
 * - ACTION from `intent:` + `action:`/`locator:` — already enriched
 * Skips non-intent shorthands (URL, WAIT_UNTIL, VERIFY, description+js, WAIT, etc.)
 */
export function countIntentStatements(statements: Statement[]): { action: number; draft: number } {
  let action = 0;
  let draft = 0;

  for (const stmt of statements) {
    if (stmt.type === StatementType.DRAFT) {
      draft++;
    } else if (stmt.type === StatementType.ACTION) {
      const actionName =
        (stmt as Action).action_entity?.action_data?.action_name ?? '';
      if (!NON_INTENT_ACTIONS.has(actionName)) {
        action++;
      }
    }
  }

  return { action, draft };
}

/**
 * Validate JS code syntax by wrapping in an async function and parsing.
 * Returns an error message if invalid, or null if OK.
 */
function validateJsSyntax(code: string): string | null {
  try {
    // Wrap in async function to allow top-level await
    new Function(`return async function() { ${code} }`);
    return null;
  } catch (e: any) {
    return e.message;
  }
}

/**
 * Validate a JS expression (for IF/WHILE conditions).
 */
function validateJsExpression(expr: string): string | null {
  try {
    new Function(`return async function() { return (${expr}) }`);
    return null;
  } catch (e: any) {
    return e.message;
  }
}

/**
 * Reject overly complex JS caches (verify js:, intent + js:). Returns an error
 * message if the cache exceeds the line or await limits, or null if OK.
 *
 * Both metrics ignore blank lines and single-line `//` comments — counting
 * `await` over the raw code would otherwise inflate the count on commented-out
 * lines that the line counter already skipped. Await count is a `\bawait\b`
 * keyword match (a heuristic, not an AST count); it exists so authors can't
 * bypass the line cap by collapsing logic onto one line.
 */
function validateJsCacheComplexity(code: string): string | null {
  const meaningfulLines = code
    .split(/\r?\n/)
    .map(line => line.trim())
    .filter(line => line.length > 0 && !line.startsWith('//'));
  const lines = meaningfulLines.length;
  const awaitMatches = meaningfulLines.join('\n').match(/\bawait\b/g);
  const awaits = awaitMatches ? awaitMatches.length : 0;

  if (lines <= MAX_JS_CACHE_LINES && awaits <= MAX_JS_CACHE_AWAITS) {
    return null;
  }

  return (
    `${lines} non-blank line(s), ${awaits} await(s) — limits are ${MAX_JS_CACHE_LINES} lines and ${MAX_JS_CACHE_AWAITS} awaits. ` +
    `The VERIFY js: field is a cache for one natural-language assertion, not a place for multi-step logic. ` +
    `Break this into multiple statements — one VERIFY per assertion — so each step is visible in the debugger and self-healable. ` +
    `For freeform setup code (mocking, storage), use the description: + js: escape hatch, which has no complexity cap.`
  );
}

/**
 * Validate a YAML test file's content.
 *
 * Returns structured results with errors (invalid YAML) and warnings
 * (low action coverage). The caller decides the VERDICT, not the rule:
 * `shiplight transpile` prints the coverage warning and still emits the spec,
 * `shiplight transpile --strict` fails on it. Use `isBelowCoverageThreshold`
 * to make that decision from `stats` rather than inspecting `warnings`.
 */
export function validateTestYaml(
  yamlContent: string,
  options?: { coverageThreshold?: number }
): ValidationResult {
  const threshold = options?.coverageThreshold ?? DEFAULT_COVERAGE_THRESHOLD;
  const errors: string[] = [];
  const warnings: string[] = [];

  let flow;
  try {
    flow = yamlToTestFlow(yamlContent);
  } catch (e: any) {
    return {
      valid: false,
      errors: [`Invalid YAML: ${e.message}`],
      warnings: [],
      stats: { total: 0, action: 0, draft: 0, coverage: 0 },
    };
  }

  if (!flow.goal) {
    errors.push('Missing required field: "goal"');
  }

  if (!flow.statements?.length) {
    errors.push('Missing required field: "statements"');
  }

  // Flatten all statements (main + teardown)
  const allStatements = [
    ...getAllStatementsInOrder(flow.statements ?? []),
    ...(flow.teardown ? getAllStatementsInOrder(flow.teardown) : []),
  ];

  const { action: actionCount, draft: draftCount } = countIntentStatements(allStatements);

  // Validate all inline JS (catch YAML escaping bugs like /\/pattern/ → //pattern/)
  const JS_HINT = 'Hint: in YAML double-quoted strings, backslashes are escape characters — use \\\\/ instead of \\/ for regex, or use single quotes.';
  for (const stmt of allStatements) {
    // Reject unresolved cloud template references — `reference_id` is a cloud-only
    // field pointing at a reusable_test_steps row. Local YAML tests must either
    // inline the template body or use the local `template:` key (resolved by the
    // YAML parser). A bare reference_id means the template was never expanded.
    const stmtAny = stmt as { reference_id?: number; description?: string };
    if (stmtAny.reference_id !== undefined) {
      const desc = stmtAny.description || stmt.uid;
      errors.push(
        `Unresolved cloud template reference on statement "${desc}" (reference_id: ${stmtAny.reference_id}). ` +
        `Local YAML tests cannot use reference_id — inline the template statements or use the local "template:" key instead.`
      );
    }

    // Validate JS code blocks in actions (VERIFY js:, JS:)
    if (stmt.type === StatementType.ACTION) {
      const action = stmt as Action;
      const actionName = action.action_entity?.action_data?.action_name ?? '';
      if (actionName === 'js_code' || actionName === 'js_action' || actionName === 'verify' || actionName === 'ai_assert') {
        const code = action.action_entity?.action_data?.kwargs?.code;
        if (typeof code === 'string') {
          const jsError = validateJsSyntax(code);
          if (jsError) {
            const desc = action.description || actionName;
            errors.push(`Invalid JS in "${desc}": ${jsError}. ${JS_HINT}`);
          } else if (actionName === 'verify') {
            // Complexity cap applies only to the verify js: cache. js_code (the
            // description: + js: escape hatch) is freeform; ai_assert and legacy
            // js_action have no capped YAML surface.
            const complexityError = validateJsCacheComplexity(code);
            if (complexityError) {
              const desc = action.description || actionName;
              errors.push(`JS cache for "${desc}" is too complex: ${complexityError}`);
            }
          }
        }
      }

      // Validate JS condition in WAIT_UNTIL (js: mode) — mirrors IF/WHILE JS validation.
      // Like IF/WHILE, only syntax is checked (no complexity cap — that's verify-only).
      if (
        actionName === 'ai_wait_until' &&
        action.action_entity?.action_data?.kwargs?.condition_type === ConditionType.JS_CODE
      ) {
        const kwargs = action.action_entity?.action_data?.kwargs;
        // The intent + sibling `js:` form stores the intent in `condition` and the
        // polled expression in `js`; the bare prefix form stores the expression in
        // `condition`. Validate whichever holds the expression.
        const expression = typeof kwargs?.js === 'string' ? kwargs.js : kwargs?.condition;
        if (typeof expression === 'string') {
          const jsError = validateJsExpression(expression);
          if (jsError) {
            errors.push(`Invalid JS in WAIT_UNTIL condition "${expression}": ${jsError}. ${JS_HINT}`);
          }
        }
      }
    }

    // Validate JS conditions in IF/WHILE
    if (stmt.type === StatementType.IF_ELSE) {
      const ifElse = stmt as IfElse;
      if (ifElse.condition.type === ConditionType.JS_CODE) {
        const jsError = validateJsExpression(ifElse.condition.expression);
        if (jsError) {
          errors.push(`Invalid JS in IF condition "${ifElse.condition.expression}": ${jsError}. ${JS_HINT}`);
        }
      }
    }
    if (stmt.type === StatementType.WHILE_LOOP) {
      const whileLoop = stmt as WhileLoop;
      if (whileLoop.condition.type === ConditionType.JS_CODE) {
        const jsError = validateJsExpression(whileLoop.condition.expression);
        if (jsError) {
          errors.push(`Invalid JS in WHILE condition "${whileLoop.condition.expression}": ${jsError}. ${JS_HINT}`);
        }
      }
    }
  }

  const total = actionCount + draftCount;
  const coveragePct = total > 0 ? Math.round((actionCount / total) * 100) : 0;

  if (total > 0 && coveragePct / 100 < threshold) {
    warnings.push(
      `Low action coverage: ${actionCount}/${total} statements (${coveragePct}%) are enriched with action/js. ` +
      `${draftCount} draft statement(s) still need enrichment. Use MCP tools (act, get_locators) to convert drafts to actions.`
    );
  }

  return {
    valid: errors.length === 0,
    errors,
    warnings,
    stats: { total, action: actionCount, draft: draftCount, coverage: coveragePct },
  };
}
