import useSWR from 'swr';
import { fetcher } from '@/utils/fetcher';
import { ReusableStep } from '@/common/models/reusableStep';
import { useCallback, useMemo } from 'react';

/**
 * Hook to fetch and manage reusable steps
 */
export function useReusableSteps(options = {}) {
  const { data, error, isLoading, mutate } = useSWR<ReusableStep[]>(
    '/api/reusable-steps',
    fetcher.get,
    {
      refreshInterval: 600000, // Refresh every 10 minutes
      dedupingInterval: 60000, // Dedupe requests within 60 seconds
      ...options
    }
  );

  // Memoize reusableSteps to prevent unnecessary re-renders when data reference changes but content is the same
  const reusableSteps = useMemo(() => data || [], [data]);

  /**
   * Refresh reusable steps
   */
  const refreshReusableSteps = async (): Promise<void> => {
    await mutate();
  };

  /**
   * Get a reusable step by its ID
   */
  const getReusableStepById = useCallback((id: number): ReusableStep | null => {
    return reusableSteps.find((step: ReusableStep) => step.id === id) || null;
  }, [reusableSteps]);

  /**
   * Get a reusable step by its name
   */
  const getReusableStepByName = useCallback((name: string): ReusableStep | null => {
    return reusableSteps.find((step: ReusableStep) => step.name === name) || null;
  }, [reusableSteps]);

  /**
   * Create a new reusable step
   */
  const createReusableStep = async (
    name: string,
    description: string,
    statements: any[]
  ): Promise<ReusableStep> => {
    try {
      const reusableStep = new ReusableStep(
        '', // organizationId will be set by backend
        0, // id will be generated by backend
        name,
        statements,
        description
      );

      const created = await fetcher.post('/api/reusable-steps', { reusableStep });
      await mutate();
      return created;
    } catch (error) {
      console.error('Error creating reusable step:', error);
      throw error;
    }
  };

  /**
   * Update a reusable step
   */
  const updateReusableStep = async (
    id: number,
    updates: Partial<ReusableStep>,
    testCaseId?: number
  ): Promise<ReusableStep> => {
    try {
      const payload = {
        ...updates,
        ...(testCaseId && { updated_by_test_case_id: testCaseId })
      };
      const updated = await fetcher.put(`/api/reusable-steps/${id}/update`, payload);
      await mutate();
      return updated;
    } catch (error) {
      console.error('Error updating reusable step:', error);
      throw error;
    }
  };

  /**
   * Delete a reusable step
   */
  const deleteReusableStep = async (id: number): Promise<void> => {
    try {
      await fetcher.delete(`/api/reusable-steps/${id}/delete`);
      await mutate();
    } catch (error) {
      console.error('Error deleting reusable step:', error);
      throw error;
    }
  };

  /**
   * Check if a reusable step name exists
   */
  const reusableStepExists = async (name: string): Promise<boolean> => {
    try {
      const exists = await fetcher.post(`/api/reusable-steps/exists/${encodeURIComponent(name)}`, {});
      return exists;
    } catch (error) {
      console.error('Error checking reusable step existence:', error);
      throw error;
    }
  };

  return {
    reusableSteps,
    isLoading,
    isError: error,
    refreshReusableSteps,
    getReusableStepById,
    getReusableStepByName,
    createReusableStep,
    updateReusableStep,
    deleteReusableStep,
    reusableStepExists,
  };
}
