/** Transpiler version — injected at build time from package.json via esbuild define. */
declare const __SHIPLIGHTAI_VERSION__: string | undefined;

export const TRANSPILER_VERSION: string =
  typeof __SHIPLIGHTAI_VERSION__ !== 'undefined'
    ? __SHIPLIGHTAI_VERSION__
    : 'dev';

/**
 * Revision of the *shape* of the generated Playwright code, independent of the
 * package version. Bump this in the same change as any edit to what the
 * transpiler emits.
 *
 * `TRANSPILER_VERSION` alone cannot invalidate the generated-spec cache during
 * development: it resolves to the literal `dev` whenever the CLI runs from
 * source, so a format change leaves every existing `.yaml.spec.ts` looking
 * up-to-date and the old output keeps running. Released builds do not have that
 * problem — the publish workflow bumps the version before building — which is
 * exactly why the gap is easy to miss until someone hits it locally.
 *
 * History:
 *   1 — in-title tag prefix, e.g. test('@smoke Login', ...)
 *   2 — Playwright tag options argument, e.g. test('Login', { tag: ['@smoke'] }, ...)
 */
export const OUTPUT_FORMAT_REVISION = 2;

/**
 * Value stamped into the `// @generated by shiplightai v...` header and compared
 * against it to decide whether a generated spec must be rebuilt. Every writer
 * and the staleness check must use this, never `TRANSPILER_VERSION` directly.
 */
export const TRANSPILER_CACHE_KEY = `${TRANSPILER_VERSION}+fmt${OUTPUT_FORMAT_REVISION}`;
