import { test, expect } from '@playwright/test';
import { transpileYamlTest, transpileYamlSuite } from '../../src/yaml-transpiler/index';
import { TRANSPILER_CACHE_KEY } from '../../src/transpiler/version';

// Call the transpiler the way production does — the real entry point plus the
// version injection — rather than through a convenience wrapper no shipping
// code path used. See apps/cli/src/transpiler/index.ts for why the wrapper was
// removed.
const transpileTestFlow: typeof transpileYamlTest = (flow, options) =>
  transpileYamlTest(flow, { ...options, version: TRANSPILER_CACHE_KEY });
const transpileSuiteFile: typeof transpileYamlSuite = (suite, options) =>
  transpileYamlSuite(suite, { ...options, version: TRANSPILER_CACHE_KEY });
import type { TestFlow, Statement, Action, Draft, Step, IfElse, WhileLoop } from 'shiplight-types';
import type { ParsedSuite } from '../../src/yamlParser';

function makeTestFlow(statements: Statement[], opts?: Partial<TestFlow>): TestFlow {
  return {
    goal: opts?.goal || 'Test',
    url: opts?.url || 'https://example.com',
    statements,
    teardown: opts?.teardown || [],
  };
}

test.describe('transpileTestFlow', () => {
  test('generates valid Playwright test structure', () => {
    const flow = makeTestFlow([]);
    const code = transpileTestFlow(flow);

    expect(code).toContain("import { test, expect } from 'shiplightai/fixture'");
    expect(code).toContain("test('Test', async ({ page, agent })");
  });

  test('includes version header for cache invalidation', () => {
    const flow = makeTestFlow([]);
    const code = transpileTestFlow(flow);
    const firstLine = code.split('\n')[0];

    // The `+fmt<N>` suffix is what invalidates already-generated specs when the
    // emitted code changes shape but the package version has not moved (it is
    // always `dev` when running from source).
    expect(firstLine).toMatch(/^\/\/ @generated by shiplightai v(\d+\.\d+\.\d+|dev)\+fmt\d+$/);
  });

  test('applies test name override', () => {
    const flow = makeTestFlow([]);
    const code = transpileTestFlow(flow, { testName: 'Custom Name' });
    expect(code).toContain("test('Custom Name'");
  });

  test('applies tags', () => {
    const flow = makeTestFlow([]);
    const code = transpileTestFlow(flow, { tags: ['smoke', 'auth'] });
    expect(code).toContain("test('Test', { tag: ['@smoke', '@auth'] }, async (");
  });

  test('applies test.use() config', () => {
    const flow = makeTestFlow([]);
    const code = transpileTestFlow(flow, { use: { headless: true } });
    expect(code).toContain('test.use(');
    expect(code).toContain('"headless": true');
  });

  test('wraps statements in try/finally when teardown exists', () => {
    const draft: Draft = { type: 'DRAFT', uid: 'd1', description: 'Do something' };
    const teardownDraft: Draft = { type: 'DRAFT', uid: 'd2', description: 'Cleanup' };
    const flow = makeTestFlow([draft], { teardown: [teardownDraft] });
    const code = transpileTestFlow(flow);

    expect(code).toContain('try {');
    expect(code).toContain('} finally {');
    expect(code).toContain('// Teardown');
  });

  /* ================================================================
   * Execution Control Annotations
   * ================================================================ */

  test.describe('execution control', () => {
    test('timeout generates test.setTimeout()', () => {
      const flow = makeTestFlow([]);
      const code = transpileTestFlow(flow, { timeout: 30000 });
      expect(code).toContain('test.setTimeout(30000)');
    });

    test('skip: true generates test.skip()', () => {
      const flow = makeTestFlow([]);
      const code = transpileTestFlow(flow, { skip: true });
      expect(code).toContain('test.skip();');
    });

    test('skip with reason generates test.skip(true, reason)', () => {
      const flow = makeTestFlow([]);
      const code = transpileTestFlow(flow, { skip: 'Blocked by bug #123' });
      expect(code).toContain("test.skip(true, 'Blocked by bug #123');");
    });

    test('fail: true generates test.fail()', () => {
      const flow = makeTestFlow([]);
      const code = transpileTestFlow(flow, { fail: true });
      expect(code).toContain('test.fail();');
    });

    test('fail with reason generates test.fail(true, reason)', () => {
      const flow = makeTestFlow([]);
      const code = transpileTestFlow(flow, { fail: 'Known bug #456' });
      expect(code).toContain("test.fail(true, 'Known bug #456');");
    });

    test('only: true generates test.only()', () => {
      const flow = makeTestFlow([]);
      const code = transpileTestFlow(flow, { only: true });
      expect(code).toContain("test.only('Test'");
      expect(code).not.toMatch(/[^.]test\('Test'/);
    });

    test('slow: true generates test.slow()', () => {
      const flow = makeTestFlow([]);
      const code = transpileTestFlow(flow, { slow: true });
      expect(code).toContain('test.slow();');
    });

    test('multiple annotations combined', () => {
      const flow = makeTestFlow([]);
      const code = transpileTestFlow(flow, { slow: true, timeout: 60000 });
      expect(code).toContain('test.slow();');
      expect(code).toContain('test.setTimeout(60000)');
    });
  });

  test.describe('DRAFT statements', () => {
    test('generates agent.run() call', () => {
      const draft: Draft = { type: 'DRAFT', uid: 'd1', description: 'Click the login button' };
      const code = transpileTestFlow(makeTestFlow([draft]));

      expect(code).toContain('// main.0: Click the login button');
      expect(code).toContain('agent.run(page, "Click the login button"');
    });

    test('skips drafts with no description', () => {
      const draft: Draft = { type: 'DRAFT', uid: 'd1', description: '' };
      const code = transpileTestFlow(makeTestFlow([draft]));
      expect(code).toContain('Skipping - no description');
    });
  });

  test.describe('ACTION statements', () => {
    test('generates agent.step() with locator for click', () => {
      const action: Action = {
        type: 'ACTION',
        uid: 'a1',
        description: 'Click Submit',
        action_entity: {
          action_description: 'Click Submit',
          locator: "getByRole('button', { name: 'Submit' })",
          action_data: { action_name: 'click', kwargs: {} },
        },
      };
      const code = transpileTestFlow(makeTestFlow([action]));

      expect(code).toContain('agent.step(page, async () =>');
      expect(code).toContain("getByRole('button', { name: 'Submit' }).first().click");
      expect(code).toContain("'a1'");
    });

    test('falls back to agent.execute() without action entity', () => {
      const action: Action = {
        type: 'ACTION',
        uid: 'a2',
        description: 'Do something complex',
      };
      const code = transpileTestFlow(makeTestFlow([action]));

      expect(code).toContain('agent.execute(page, "Do something complex"');
    });

    test('generates input_text with execAction', () => {
      const action: Action = {
        type: 'ACTION',
        uid: 'a3',
        description: 'Type email',
        action_entity: {
          action_description: 'Type email',
          locator: "getByLabel('Email')",
          action_data: { action_name: 'input_text', kwargs: { text: 'user@test.com' } },
        },
      };
      const code = transpileTestFlow(makeTestFlow([action]));

      expect(code).toContain('agent.execAction("input_text"');
      expect(code).toContain('"user@test.com"');
    });

    test('generates press with page.keyboard', () => {
      const action: Action = {
        type: 'ACTION',
        uid: 'a4',
        description: 'Press Enter',
        action_entity: {
          action_description: 'Press Enter',
          action_data: { action_name: 'press', kwargs: { keys: 'Enter' } },
        },
      };
      const code = transpileTestFlow(makeTestFlow([action]));

      expect(code).toContain('page.keyboard.press("Enter")');
    });

    test('generates AI actions without step wrapper', () => {
      const action: Action = {
        type: 'ACTION',
        uid: 'a5',
        description: 'Verify user is logged in',
        action_entity: {
          action_description: 'Verify user is logged in',
          action_data: { action_name: 'verify', kwargs: { statement: 'User is logged in' } },
        },
      };
      const code = transpileTestFlow(makeTestFlow([action]));

      expect(code).toContain('agent.assert(page');
      expect(code).not.toContain('agent.step(page');
    });

    test('generates go_to_url with execAction', () => {
      const action: Action = {
        type: 'ACTION',
        uid: 'a6',
        description: 'Navigate',
        action_entity: {
          action_description: 'Navigate',
          action_data: { action_name: 'go_to_url', kwargs: { url: 'https://test.com' } },
        },
      };
      const code = transpileTestFlow(makeTestFlow([action]));

      expect(code).toContain('agent.execAction("go_to_url"');
      expect(code).toContain('"https://test.com"');
    });

    test('generates function with file#export import', () => {
      const action: Action = {
        type: 'ACTION',
        uid: 'a7',
        description: 'Run login helper',
        action_entity: {
          action_description: 'Run login helper',
          action_data: {
            action_name: 'function',
            kwargs: {
              functionName: 'helpers/auth.ts#loginUser',
              args: ['page'],
            },
          },
        },
      };
      const code = transpileTestFlow(makeTestFlow([action]), {
        projectRoot: '/project',
        yamlDir: '/project/tests',
      });

      expect(code).toContain("import { loginUser } from '../helpers/auth'");
      expect(code).toContain('await loginUser(page)');
    });

    test('throws a runtime error for absolute paths in file#export references', () => {
      const action: Action = {
        type: 'ACTION',
        uid: 'a7-abs',
        description: 'Run login helper',
        action_entity: {
          action_description: 'Run login helper',
          action_data: {
            action_name: 'function',
            kwargs: {
              functionName: '/project/helpers/auth.ts#loginUser',
              args: ['page'],
            },
          },
        },
      };
      const code = transpileTestFlow(makeTestFlow([action]), {
        projectRoot: '/project',
        yamlDir: '/project/tests',
      });

      expect(code).toContain('throw new Error(');
      expect(code).toContain('Absolute paths are not supported in call: references');
    });

    test('generates js_code as inline block', () => {
      const action: Action = {
        type: 'ACTION',
        uid: 'a8',
        description: 'Custom JS',
        action_entity: {
          action_description: 'Custom JS',
          action_data: {
            action_name: 'js_code',
            kwargs: { code: 'console.log("hello");\nconsole.log("world");' },
          },
        },
      };
      const code = transpileTestFlow(makeTestFlow([action]));

      expect(code).toContain('console.log("hello")');
      expect(code).toContain('console.log("world")');
    });

    test('generates js_code from JS shorthand as inline block', () => {
      const action: Action = {
        type: 'ACTION',
        uid: 'a-js',
        description: 'JS code block',
        action_entity: {
          action_description: 'JS code block',
          action_data: {
            action_name: 'js_code',
            kwargs: { code: "await page.route('**/api', r => r.abort());" },
          },
        },
      };
      const code = transpileTestFlow(makeTestFlow([action]));

      expect(code).toContain("await page.route('**/api', r => r.abort());");
    });

    test('throws at runtime for unknown action name', () => {
      const action: Action = {
        type: 'ACTION',
        uid: 'a-unknown',
        description: 'Some step',
        action_entity: {
          action_description: 'Some step',
          action_data: { action_name: 'not_a_real_action', kwargs: {} },
        },
      };
      const code = transpileTestFlow(makeTestFlow([action]));

      expect(code).toContain('throw new Error("Unknown action: not_a_real_action")');
    });

    test('passes {{VAR}} through as literal string for runtime resolution', () => {
      const action: Action = {
        type: 'ACTION',
        uid: 'a9',
        description: 'Type username',
        action_entity: {
          action_description: 'Type username',
          locator: "getByLabel('Username')",
          action_data: { action_name: 'input_text', kwargs: { text: '{{TEST_USER}}' } },
        },
      };
      const code = transpileTestFlow(makeTestFlow([action]));

      expect(code).toContain('{{TEST_USER}}');
      expect(code).not.toContain('process.env');
    });
  });

  test.describe('STEP statements', () => {
    test('generates comment and nested statements', () => {
      const step: Step = {
        type: 'STEP',
        uid: 's1',
        description: 'Login flow',
        statements: [
          { type: 'DRAFT', uid: 'd1', description: 'Enter email' } as Draft,
          { type: 'DRAFT', uid: 'd2', description: 'Enter password' } as Draft,
        ],
      };
      const code = transpileTestFlow(makeTestFlow([step]));

      expect(code).toContain('// Step: Login flow');
      expect(code).toContain('// main.0.0: Enter email');
      expect(code).toContain('// main.0.1: Enter password');
    });
  });

  test.describe('IF_ELSE statements', () => {
    test('generates JS condition', () => {
      const ifElse: IfElse = {
        type: 'IF_ELSE',
        uid: 'ie1',
        condition: { type: 'JS_CODE', expression: 'page.url().includes("login")' },
        then: [{ type: 'DRAFT', uid: 'd1', description: 'Already on login' } as Draft],
        else: [{ type: 'DRAFT', uid: 'd2', description: 'Go to login' } as Draft],
      };
      const code = transpileTestFlow(makeTestFlow([ifElse]));

      expect(code).toContain('if (page.url().includes("login"))');
      expect(code).toContain('} else {');
    });

    test('generates AI condition with agent.evaluate', () => {
      const ifElse: IfElse = {
        type: 'IF_ELSE',
        uid: 'ie2',
        condition: { type: 'AI_MODE', expression: 'User sees a modal' },
        then: [{ type: 'DRAFT', uid: 'd1', description: 'Close modal' } as Draft],
      };
      const code = transpileTestFlow(makeTestFlow([ifElse]));

      expect(code).toContain('agent.evaluate(page');
      expect(code).toContain('"User sees a modal"');
    });
  });

  test.describe('WHILE_LOOP statements', () => {
    test('generates loop with timeout checking', () => {
      const whileLoop: WhileLoop = {
        type: 'WHILE_LOOP',
        uid: 'wl1',
        condition: { type: 'AI_MODE', expression: 'There are more items' },
        body: [{ type: 'DRAFT', uid: 'd1', description: 'Process item' } as Draft],
        timeout_ms: 30000,
      };
      const code = transpileTestFlow(makeTestFlow([whileLoop]));

      expect(code).toContain('Date.now()');
      expect(code).toContain('30000');
      expect(code).toContain('agent.evaluate(page');
      expect(code).toContain('"There are more items"');
    });

    test('generates JS condition loop', () => {
      const whileLoop: WhileLoop = {
        type: 'WHILE_LOOP',
        uid: 'wl2',
        condition: { type: 'JS_CODE', expression: 'counter < 5' },
        body: [{ type: 'DRAFT', uid: 'd1', description: 'Increment' } as Draft],
      };
      const code = transpileTestFlow(makeTestFlow([whileLoop]));

      expect(code).toContain('counter < 5');
    });
  });

  /* ================================================================
   * Feature 12: Lifecycle Hooks (single-test)
   * ================================================================ */

  test.describe('single-test hooks', () => {
    test('generates beforeEach hook', () => {
      const flow = makeTestFlow([]);
      const code = transpileTestFlow(flow, {
        beforeEach: [
          { action: 'go_to_url', description: 'Navigate to page', url: 'https://example.com' },
        ],
      });

      expect(code).toContain('test.beforeEach(async ({ page, agent }) => {');
      expect(code).toContain('go_to_url');
    });

    test('generates afterEach hook', () => {
      const flow = makeTestFlow([]);
      const code = transpileTestFlow(flow, {
        afterEach: [
          { intent: 'Clear session state' },
        ],
      });

      expect(code).toContain('test.afterEach(async ({ page, agent }) => {');
    });
  });

  /* ================================================================
   * Feature 13: Parameterized Tests (single-test)
   * ================================================================ */

  test.describe('parameterized tests', () => {
    test('generates separate test per parameter set with saveVariable calls', () => {
      const draft: Draft = { type: 'DRAFT', uid: 'd1', description: 'Enter {{username}}' };
      const flow = makeTestFlow([draft], { url: 'https://example.com' });
      const code = transpileTestFlow(flow, {
        testName: 'Login test',
        parameters: [
          { name: 'admin', values: { username: 'admin@test.com' } },
          { name: 'editor', values: { username: 'editor@test.com' } },
        ],
      });

      expect(code).toContain("test('Login test [admin]'");
      expect(code).toContain("test('Login test [editor]'");
      // Values are set via saveVariable, not inline substitution
      expect(code).toContain('agent.agentServices.saveVariable("username", "admin@test.com")');
      expect(code).toContain('agent.agentServices.saveVariable("username", "editor@test.com")');
      // {{username}} is preserved for runtime resolution
      expect(code).toContain('{{username}}');
    });

    test('emits the parameter name as a Playwright tag via the options form', () => {
      const draft: Draft = { type: 'DRAFT', uid: 'd1', description: 'Enter {{username}}' };
      const flow = makeTestFlow([draft], { url: 'https://example.com' });
      const code = transpileTestFlow(flow, {
        testName: 'Login test',
        parameters: [
          { name: 'admin', values: { username: 'admin@test.com' } },
          { name: 'editor', values: { username: 'editor@test.com' } },
        ],
      });

      // Tag enables `--grep '@admin'` filtering without bracket escaping.
      expect(code).toContain("test('Login test [admin]', { tag: ['@admin'] }, async (");
      expect(code).toContain("test('Login test [editor]', { tag: ['@editor'] }, async (");
    });

    test('multi-word parameter names produce multi-word tags (options form keeps the space)', () => {
      const draft: Draft = { type: 'DRAFT', uid: 'd1', description: 'Add {{product}}' };
      const flow = makeTestFlow([draft], { url: 'https://example.com' });
      const code = transpileTestFlow(flow, {
        testName: 'Add to cart',
        parameters: [
          { name: 'backpack', values: { product: 'Backpack' } },
          { name: 'bike light', values: { product: 'Bike Light' } },
        ],
      });

      expect(code).toContain("test('Add to cart [backpack]', { tag: ['@backpack'] }, async (");
      expect(code).toContain("test('Add to cart [bike light]', { tag: ['@bike light'] }, async (");
    });

    test('escapes quotes and backslashes in the tag (no string-literal breakout)', () => {
      const flow = makeTestFlow([], { url: 'https://example.com' });
      const code = transpileTestFlow(flow, {
        testName: 'Test',
        parameters: [
          { name: "it's", values: {} },
          { name: 'a\\b', values: {} },
        ],
      });

      // Single quote and backslash must be escaped so the generated tag string
      // literal stays well-formed (guards against code injection via param names).
      expect(code).toContain("{ tag: ['@it\\'s'] }");
      expect(code).toContain("{ tag: ['@a\\\\b'] }");
    });

    test('non-parameterized tests do not get a tag option', () => {
      const flow = makeTestFlow([], { url: 'https://example.com' });
      const code = transpileTestFlow(flow, { testName: 'Plain test' });

      expect(code).toContain("test('Plain test', async (");
      expect(code).not.toContain('{ tag:');
    });

    test('preserves {{var}} in statements for runtime resolution', () => {
      const draft: Draft = { type: 'DRAFT', uid: 'd1', description: 'Go to {{path}}' };
      const flow = makeTestFlow([draft], { url: 'https://example.com' });
      const code = transpileTestFlow(flow, {
        testName: 'URL test',
        parameters: [
          { name: 'home', values: { path: 'home' } },
        ],
      });

      expect(code).toContain("test('URL test [home]'");
      // {{path}} is preserved for runtime resolution, not substituted
      expect(code).toContain('{{path}}');
      expect(code).toContain('agent.agentServices.saveVariable("path", "home")');
    });

    test('unmatched {{VAR}} passes through', () => {
      const draft: Draft = { type: 'DRAFT', uid: 'd1', description: 'Use {{UNKNOWN}}' };
      const flow = makeTestFlow([draft]);
      const code = transpileTestFlow(flow, {
        parameters: [
          { name: 'set1', values: { other: 'value' } },
        ],
      });

      expect(code).toContain('{{UNKNOWN}}');
    });
  });
});

/* ================================================================
 * YAML `tags:` → Playwright tag option
 * ================================================================ */

test.describe('tags', () => {
  const flow = (): TestFlow => makeTestFlow([], { url: 'https://example.com' });

  test('emits tags via the options form, never as a title prefix', () => {
    const code = transpileTestFlow(flow(), {
      testName: 'Mobile inventory browsing',
      tags: ['smoke', 'mobile'],
    });

    expect(code).toContain(
      "test('Mobile inventory browsing', { tag: ['@smoke', '@mobile'] }, async (",
    );
    // The title must stay clean: the reporter uploads `test.title` verbatim as
    // the cloud test-case name, so a prefix would rename the test case to
    // "@smoke @mobile Mobile inventory browsing".
    expect(code).not.toContain("test('@smoke");
  });

  test('normalizes a leading @ so an already-prefixed YAML tag is not doubled', () => {
    const code = transpileTestFlow(flow(), { testName: 'T', tags: ['@smoke', 'auth'] });

    expect(code).toContain("test('T', { tag: ['@smoke', '@auth'] }, async (");
    expect(code).not.toContain('@@smoke');
  });

  test('drops empty and whitespace-only tags', () => {
    const code = transpileTestFlow(flow(), { testName: 'T', tags: ['', '  ', 'smoke'] });

    expect(code).toContain("test('T', { tag: ['@smoke'] }, async (");
  });

  test('omits the tag option entirely when every tag is empty', () => {
    const code = transpileTestFlow(flow(), { testName: 'T', tags: ['', '  '] });

    expect(code).toContain("test('T', async (");
    expect(code).not.toContain('{ tag:');
  });

  test('escapes quotes and backslashes in tags (no string-literal breakout)', () => {
    const code = transpileTestFlow(flow(), { testName: 'T', tags: ["it's", 'a\\b'] });

    expect(code).toContain("{ tag: ['@it\\'s', '@a\\\\b'] }");
  });

  test('merges file tags with the parameter-set tag, file tags first', () => {
    const code = transpileTestFlow(flow(), {
      testName: 'Login test',
      tags: ['smoke'],
      parameters: [{ name: 'admin', values: { username: 'a@test.com' } }],
    });

    expect(code).toContain("test('Login test [admin]', { tag: ['@smoke', '@admin'] }, async (");
  });

  test('keeps transpiling when YAML yields a non-string tag', () => {
    // Regression: unquoted YAML scalars (`tags: [2026]` — a year, a version, a
    // ticket number) reach the transpiler as numbers, because the parser casts
    // `tags` without checking element types. Throwing here is not a loud
    // failure: on a bare `shiplight test` the transpile error is swallowed and
    // the file is skipped, so a gating test vanishes from a green run.
    const code = transpileTestFlow(flow(), {
      testName: 'T',
      tags: [2026 as unknown as string, true as unknown as string, 'smoke'],
    });

    expect(code).toContain("test('T', { tag: ['@2026', '@true', '@smoke'] }, async (");
  });

  test('drops a map or sequence tag rather than coercing it to nonsense', () => {
    // `String({})` is '[object Object]' — a tag Playwright accepts and no grep
    // will ever select, so the test looks tagged but is unreachable.
    const code = transpileTestFlow(flow(), {
      testName: 'T',
      tags: [{ k: 'v' } as unknown as string, ['x', 'y'] as unknown as string, 'smoke'],
    });

    expect(code).toContain("test('T', { tag: ['@smoke'] }, async (");
    expect(code).not.toContain('object Object');
  });

  test('drops a tag that is only @ characters', () => {
    // Guards the order of strip-then-filter: filtering before stripping would
    // emit a bare '@' tag, which Playwright accepts and no grep will select.
    const code = transpileTestFlow(flow(), { testName: 'T', tags: ['@', '@@', 'smoke'] });

    expect(code).toContain("test('T', { tag: ['@smoke'] }, async (");
  });

  test('trims surrounding whitespace but keeps the tag', () => {
    const code = transpileTestFlow(flow(), { testName: 'T', tags: ['  smoke  ', '@ auth'] });

    expect(code).toContain("test('T', { tag: ['@smoke', '@auth'] }, async (");
  });

  test('dedupes within a single tag list, including mixed @ spellings', () => {
    const code = transpileTestFlow(flow(), { testName: 'T', tags: ['smoke', '@smoke'] });

    expect(code).toContain("test('T', { tag: ['@smoke'] }, async (");
  });

  test('keeps a multi-word file-level tag intact', () => {
    // The in-title form could not express this: the `@\S+` recognizer truncates
    // at the space, which is one of the reasons for the options form.
    const code = transpileTestFlow(flow(), { testName: 'T', tags: ['slow path'] });

    expect(code).toContain("test('T', { tag: ['@slow path'] }, async (");
  });

  test('does not repeat a tag when the parameter name matches a file tag', () => {
    const code = transpileTestFlow(flow(), {
      testName: 'Login test',
      tags: ['admin'],
      parameters: [{ name: 'admin', values: {} }],
    });

    expect(code).toContain("test('Login test [admin]', { tag: ['@admin'] }, async (");
  });
});

/* ================================================================
 * transpileSuiteFile
 * ================================================================ */

test.describe('transpileSuiteFile', () => {
  function makeSuite(overrides?: Partial<ParsedSuite>): ParsedSuite {
    return {
      tests: [
        {
          testFlow: {
            goal: 'Test A',
            url: 'https://example.com',
            statements: [{ type: 'DRAFT', uid: 'd1', description: 'Step A' } as Draft],
            teardown: [],
          },
          name: 'Test A',
        },
      ],
      ...overrides,
    };
  }

  test('generates test.describe() with test()', () => {
    const suite = makeSuite();
    const code = transpileSuiteFile(suite, { testName: 'My Suite' });

    expect(code).toContain("import { test, expect } from 'shiplightai/fixture'");
    // Full `() => {` tail so an empty tag list emitting `, { tag: [] }` fails here.
    expect(code).toContain("test.describe.serial('My Suite', () => {");
    expect(code).toContain("test('Test A', async ({ page, agent })");
    expect(code).toContain('});');
  });

  test('applies tags to describe block via the options form', () => {
    const suite = makeSuite();
    const code = transpileSuiteFile(suite, { testName: 'Suite', tags: ['smoke', 'e2e'] });

    expect(code).toContain("test.describe.serial('Suite', { tag: ['@smoke', '@e2e'] }, () => {");
    expect(code).not.toContain("test.describe.serial('@smoke");
  });

  test('emits per-test tags declared inside a suite', () => {
    // Regression: `ParsedSuiteTest.tags` was parsed from YAML but never
    // transpiled, so a tag on an individual suite test silently did nothing.
    const suite = makeSuite({
      tests: [
        {
          testFlow: {
            goal: 'Test A',
            url: 'https://example.com/a',
            statements: [{ type: 'DRAFT', uid: 'd1', description: 'A' } as Draft],
            teardown: [],
          },
          name: 'Test A',
          tags: ['auth', 'slow-path'],
        },
      ],
    });
    const code = transpileSuiteFile(suite, { testName: 'Suite' });

    expect(code).toContain("test('Test A', { tag: ['@auth', '@slow-path'] }, async (");
  });

  test('does not repeat the suite-level tags on each test inside it', () => {
    // Playwright already applies a describe's tags to every test within it, so
    // re-emitting them per test would list each one twice in `test.tags` and in
    // Playwright's own reporters. This pins that decision: merging the two
    // levels would be an easy-looking "fix" that silently doubles every tag.
    //
    // It also guards the title: the reporter matches a suite test back to its
    // YAML by `t.name === title` (apps/cli/src/reporter/index.ts), so a tag
    // prefix in the title would drop step enrichment for every tagged test.
    const suite = makeSuite({
      tests: [
        {
          testFlow: {
            goal: 'Test A',
            url: 'https://example.com/a',
            statements: [{ type: 'DRAFT', uid: 'd1', description: 'A' } as Draft],
            teardown: [],
          },
          name: 'Test A',
          tags: ['auth'],
        },
      ],
    });
    const code = transpileSuiteFile(suite, { testName: 'Suite', tags: ['smoke'] });

    expect(code).toContain("test.describe.serial('Suite', { tag: ['@smoke'] }, () => {");
    expect(code).toContain("test('Test A', { tag: ['@auth'] }, async (");
    expect(code).not.toContain("test('@auth");
  });

  test('does not repeat a suite-level tag when a parameter set shares its name', () => {
    // Regression: the suite-tag subtraction ran before the parameter-set name
    // was merged in, so a param set named after a suite tag re-added it and
    // Playwright reported ['@smoke', '@auth', '@smoke'].
    const suite = makeSuite({
      tests: [
        {
          testFlow: {
            goal: 'Login',
            url: 'https://example.com',
            statements: [{ type: 'DRAFT', uid: 'd1', description: 'Enter {{user}}' } as Draft],
            teardown: [],
          },
          name: 'Login',
          tags: ['auth'],
          parameters: [{ name: 'smoke', values: { user: 'a@test.com' } }],
        },
      ],
    });
    const code = transpileSuiteFile(suite, { testName: 'Suite', tags: ['smoke'] });

    expect(code).toContain("test('Login [smoke]', { tag: ['@auth'] }, async (");
  });

  test('drops a tag from a suite test that already declares it at suite level', () => {
    const suite = makeSuite({
      tests: [
        {
          testFlow: {
            goal: 'Test A',
            url: 'https://example.com/a',
            statements: [{ type: 'DRAFT', uid: 'd1', description: 'A' } as Draft],
            teardown: [],
          },
          name: 'Test A',
          tags: ['smoke', 'auth'],
        },
      ],
    });
    const code = transpileSuiteFile(suite, { testName: 'Suite', tags: ['smoke'] });

    // `@smoke` comes from the describe; only `@auth` is new to this test.
    expect(code).toContain("test('Test A', { tag: ['@auth'] }, async (");
  });

  test('merges per-test tags with the parameter-set tag in a suite', () => {
    const suite = makeSuite({
      tests: [
        {
          testFlow: {
            goal: 'Login',
            url: 'https://example.com',
            statements: [{ type: 'DRAFT', uid: 'd1', description: 'Enter {{user}}' } as Draft],
            teardown: [],
          },
          name: 'Login',
          tags: ['auth'],
          parameters: [{ name: 'admin', values: { user: 'admin@test.com' } }],
        },
      ],
    });
    const code = transpileSuiteFile(suite, { testName: 'Suite' });

    expect(code).toContain("test('Login [admin]', { tag: ['@auth', '@admin'] }, async (");
  });

  test('suite tests without tags get no tag option', () => {
    const suite = makeSuite();
    const code = transpileSuiteFile(suite, { testName: 'Suite' });

    expect(code).toContain("test('Test A', async (");
  });

  test('applies test.use() outside describe', () => {
    const suite = makeSuite();
    const code = transpileSuiteFile(suite, { testName: 'Suite', use: { headless: true } });

    expect(code).toContain('test.use(');
    expect(code).toContain('"headless": true');
    // test.use should come before test.describe
    const useIdx = code.indexOf('test.use(');
    const describeIdx = code.indexOf('test.describe.serial(');
    expect(useIdx).toBeLessThan(describeIdx);
  });

  test('generates multiple tests', () => {
    const suite = makeSuite({
      tests: [
        {
          testFlow: {
            goal: 'Test A',
            url: 'https://example.com/a',
            statements: [{ type: 'DRAFT', uid: 'd1', description: 'A' } as Draft],
            teardown: [],
          },
          name: 'Test A',
        },
        {
          testFlow: {
            goal: 'Test B',
            url: 'https://example.com/b',
            statements: [{ type: 'DRAFT', uid: 'd2', description: 'B' } as Draft],
            teardown: [],
          },
          name: 'Test B',
        },
      ],
    });
    const code = transpileSuiteFile(suite, { testName: 'Suite' });

    expect(code).toContain("test('Test A'");
    expect(code).toContain("test('Test B'");
  });

  /* ================================================================
   * Execution Control (suite tests)
   * ================================================================ */

  test.describe('suite execution control', () => {
    test('skip on suite test generates test.skip()', () => {
      const suite = makeSuite({
        tests: [{
          testFlow: {
            goal: 'Skipped',
            url: 'https://example.com',
            statements: [{ type: 'DRAFT', uid: 'd1', description: 'Step' } as Draft],
            teardown: [],
          },
          name: 'Skipped Test',
          skip: true,
        }],
      });
      const code = transpileSuiteFile(suite, { testName: 'Suite' });
      expect(code).toContain('test.skip();');
    });

    test('only on suite test generates test.only()', () => {
      const suite = makeSuite({
        tests: [{
          testFlow: {
            goal: 'Focused',
            url: 'https://example.com',
            statements: [{ type: 'DRAFT', uid: 'd1', description: 'Step' } as Draft],
            teardown: [],
          },
          name: 'Focused Test',
          only: true,
        }],
      });
      const code = transpileSuiteFile(suite, { testName: 'Suite' });
      expect(code).toContain("test.only('Focused Test'");
    });

    test('timeout on suite test generates test.setTimeout()', () => {
      const suite = makeSuite({
        tests: [{
          testFlow: {
            goal: 'Slow',
            url: 'https://example.com',
            statements: [{ type: 'DRAFT', uid: 'd1', description: 'Step' } as Draft],
            teardown: [],
          },
          name: 'Slow Test',
          timeout: 60000,
        }],
      });
      const code = transpileSuiteFile(suite, { testName: 'Suite' });
      expect(code).toContain('test.setTimeout(60000)');
    });
  });

  /* ================================================================
   * Feature 12: Suite Hooks
   * ================================================================ */

  test.describe('suite hooks', () => {
    test('generates beforeAll with browser.newPage()', () => {
      const suite = makeSuite({
        beforeAll: [{ intent: 'Setup global state' }],
      });
      const code = transpileSuiteFile(suite, { testName: 'Suite' });

      expect(code).toContain('test.beforeAll(async ({ browser }, workerInfo) => {');
      expect(code).toContain('const page = await browser.newPage({ baseURL: workerInfo.project.use.baseURL });');
      expect(code).toContain('await page.close();');
    });

    test('generates afterAll with browser.newPage()', () => {
      const suite = makeSuite({
        afterAll: [{ intent: 'Cleanup state' }],
      });
      const code = transpileSuiteFile(suite, { testName: 'Suite' });

      expect(code).toContain('test.afterAll(async ({ browser }, workerInfo) => {');
      expect(code).toContain('const page = await browser.newPage({ baseURL: workerInfo.project.use.baseURL });');
      expect(code).toContain('await page.close();');
    });

    test('generates beforeEach with page fixture', () => {
      const suite = makeSuite({
        beforeEach: [{ intent: 'Navigate to page' }],
      });
      const code = transpileSuiteFile(suite, { testName: 'Suite' });

      expect(code).toContain('test.beforeEach(async ({ page, agent }) => {');
    });

    test('generates afterEach with page fixture', () => {
      const suite = makeSuite({
        afterEach: [{ intent: 'Reset state' }],
      });
      const code = transpileSuiteFile(suite, { testName: 'Suite' });

      expect(code).toContain('test.afterEach(async ({ page, agent }) => {');
    });

    test('hooks appear inside describe block', () => {
      const suite = makeSuite({
        beforeAll: [{ intent: 'Setup' }],
        afterAll: [{ intent: 'Cleanup' }],
      });
      const code = transpileSuiteFile(suite, { testName: 'Suite' });

      const describeIdx = code.indexOf('test.describe.serial(');
      const beforeAllIdx = code.indexOf('test.beforeAll(');
      const afterAllIdx = code.indexOf('test.afterAll(');
      const closingIdx = code.lastIndexOf('});');

      expect(beforeAllIdx).toBeGreaterThan(describeIdx);
      expect(afterAllIdx).toBeGreaterThan(describeIdx);
      expect(beforeAllIdx).toBeLessThan(closingIdx);
      expect(afterAllIdx).toBeLessThan(closingIdx);
    });
  });

  /* ================================================================
   * Suite Test Teardown
   * ================================================================ */

  test.describe('suite test teardown', () => {
    test('generates try/finally when suite test has teardown', () => {
      const suite = makeSuite({
        tests: [
          {
            testFlow: {
              goal: 'Test with cleanup',
              url: 'https://example.com',
              statements: [{ type: 'DRAFT', uid: 'd1', description: 'Do something' } as Draft],
              teardown: [{ type: 'DRAFT', uid: 't1', description: 'Clean up' } as Draft],
            },
            name: 'Test with cleanup',
          },
        ],
      });
      const code = transpileSuiteFile(suite, { testName: 'Suite' });

      expect(code).toContain('try {');
      expect(code).toContain('} finally {');
      expect(code).toContain('// Teardown');
    });

    test('does not generate try/finally when suite test has empty teardown', () => {
      const suite = makeSuite();
      const code = transpileSuiteFile(suite, { testName: 'Suite' });

      expect(code).not.toContain('try {');
      expect(code).not.toContain('finally');
    });

    test('teardown appears inside the correct test block', () => {
      const suite = makeSuite({
        tests: [
          {
            testFlow: {
              goal: 'Test A',
              url: 'https://example.com',
              statements: [{ type: 'DRAFT', uid: 'd1', description: 'Step A' } as Draft],
              teardown: [],
            },
            name: 'Test A',
          },
          {
            testFlow: {
              goal: 'Test B',
              url: 'https://example.com',
              statements: [{ type: 'DRAFT', uid: 'd2', description: 'Step B' } as Draft],
              teardown: [{ type: 'DRAFT', uid: 't1', description: 'Cleanup B' } as Draft],
            },
            name: 'Test B',
          },
        ],
      });
      const code = transpileSuiteFile(suite, { testName: 'Suite' });

      // Test A should not have try/finally
      const testAIdx = code.indexOf("test('Test A'");
      const testBIdx = code.indexOf("test('Test B'");
      const tryIdx = code.indexOf('try {');

      // try/finally should only appear in Test B's block
      expect(tryIdx).toBeGreaterThan(testBIdx);
    });
  });

  /* ================================================================
   * Feature 13: Parameterized Suite Tests
   * ================================================================ */

  test.describe('parameterized suite tests', () => {
    test('generates separate test per parameter set in suite with saveVariable calls', () => {
      const suite = makeSuite({
        tests: [
          {
            testFlow: {
              goal: 'Login',
              url: 'https://example.com',
              statements: [{ type: 'DRAFT', uid: 'd1', description: 'Enter {{email}}' } as Draft],
              teardown: [],
            },
            name: 'Login',
            parameters: [
              { name: 'admin', values: { email: 'admin@test.com' } },
              { name: 'user', values: { email: 'user@test.com' } },
            ],
          },
        ],
      });
      const code = transpileSuiteFile(suite, { testName: 'Suite' });

      expect(code).toContain("test('Login [admin]'");
      expect(code).toContain("test('Login [user]'");
      // Values are set via saveVariable, not inline substitution
      expect(code).toContain('agent.agentServices.saveVariable("email", "admin@test.com")');
      expect(code).toContain('agent.agentServices.saveVariable("email", "user@test.com")');
      // {{email}} is preserved for runtime resolution
      expect(code).toContain('{{email}}');
    });

    test('emits the parameter name as a tag for each suite variant', () => {
      const suite = makeSuite({
        tests: [
          {
            testFlow: {
              goal: 'Login',
              url: 'https://example.com',
              statements: [{ type: 'DRAFT', uid: 'd1', description: 'Enter {{email}}' } as Draft],
              teardown: [],
            },
            name: 'Login',
            parameters: [
              { name: 'admin', values: { email: 'admin@test.com' } },
              { name: 'user', values: { email: 'user@test.com' } },
            ],
          },
        ],
      });
      const code = transpileSuiteFile(suite, { testName: 'Suite' });

      expect(code).toContain("test('Login [admin]', { tag: ['@admin'] }, async (");
      expect(code).toContain("test('Login [user]', { tag: ['@user'] }, async (");
    });
  });
});
