/**
 * Playwright Debug Runner
 *
 * Generates a temporary Playwright test file that bootstraps the debugger
 * inside a Playwright test context. This gives the debugger access to all
 * Playwright config features (baseURL, storageState, viewport, auth, etc.)
 * without needing to replicate them.
 */

import * as fs from "fs";
import * as path from "path";
import { spawn, type ChildProcess } from "child_process";
import { parse as parseYaml } from "yaml";

// Per-closure idempotent unlink — OLD/NEW spawns share the spec path but
// not the flag, so the OLD child's deferred close handler can't delete the
// NEW spawn's freshly-written spec file. Covered by tests.
export function makeIdempotentFileCleaner(filePath: string): () => void {
  let alreadyCleaned = false;
  return () => {
    if (alreadyCleaned) return;
    alreadyCleaned = true;
    // ENOENT is expected (file already gone). Other errors are swallowed
    // intentionally — this is a tolerant cleanup helper, not a destructive
    // delete; any failure here is a best-effort no-op.
    try { fs.unlinkSync(filePath); } catch {}
  };
}

/**
 * Build the `use` block for the debugger's temporary spec from a parsed YAML doc.
 *
 * The debugger generates its own spec instead of going through the transpiler,
 * which makes it a third independent reader of `base_url` — so it has to agree
 * with the other two or `shiplight debug` and `shiplight test` disagree about
 * the same file (issue #2209). Matching the transpiler means:
 *   - accept both spellings, top-level `base_url:` and nested `suite.base_url:`,
 *     with the nested one winning as the more specific key;
 *   - let `base_url` take precedence over `use.baseURL`.
 *
 * Exported for testing.
 */
export function resolveDebugUseBlock(rawDoc: unknown): Record<string, unknown> | undefined {
  const isRecord = (value: unknown): value is Record<string, unknown> =>
    typeof value === "object" && value !== null && !Array.isArray(value);

  const doc = isRecord(rawDoc) ? rawDoc : undefined;

  let use: Record<string, unknown> | undefined;
  if (isRecord(doc?.use)) {
    use = doc.use;
  }

  const suite = isRecord(doc?.suite) ? doc.suite : undefined;
  const baseUrl = suite?.base_url ?? doc?.base_url;
  if (baseUrl) {
    use = { ...use, baseURL: baseUrl };
  }

  return use;
}

/**
 * Find the Playwright config file by walking up from startDir.
 */
export function findPlaywrightConfig(startDir: string): string | null {
  const configNames = [
    "playwright.config.ts",
    "playwright.config.js",
    "playwright.config.mjs",
  ];
  let dir = path.resolve(startDir);
  while (true) {
    for (const name of configNames) {
      const p = path.join(dir, name);
      if (fs.existsSync(p)) return p;
    }
    const parent = path.dirname(dir);
    if (parent === dir) break;
    dir = parent;
  }
  return null;
}

/**
 * Generate the temporary debug test file content.
 *
 * We add `--remote-debugging-port=0` to Chromium's launch args so Chromium
 * picks its own free port and writes the chosen port + WS path into its
 * user-data-dir's `DevToolsActivePort` file. The inner discovers Chromium's
 * pid (a descendant of the Playwright worker), reads `--user-data-dir=…` from
 * its command line, then reads the file. No port pre-allocation, no races
 * with other Chrome instances camping 9222/9223.
 *
 * Note: we intentionally don't pass `--user-data-dir` here. Playwright
 * rejects that arg for `browser.launch()` (it insists on
 * `launchPersistentContext`). Letting Playwright manage the dir is fine —
 * we just have to discover the path, not control it.
 */
function generateDebugTestCode(
  yamlFilePath: string,
  internalPort: number,
  use?: Record<string, unknown>,
  projectRoot?: string,
): string {
  const mergedUse: Record<string, unknown> = { ...use };
  const existingArgs = ((mergedUse.launchOptions as any)?.args as string[]) ?? [];
  mergedUse.launchOptions = {
    ...((mergedUse.launchOptions as any) ?? {}),
    args: [...existingArgs, "--remote-debugging-port=0"],
  };
  const useBlock = `\ntest.use(${JSON.stringify(mergedUse)});\n`;

  return `// @generated by shiplightai — temporary debug test
import { test } from 'shiplightai/fixture';
${useBlock}
test('__shiplight_debug__', async ({ page, agent, testContext }) => {
  // Disable timeout — debugger runs until user stops it
  test.setTimeout(0);

  const { startPlaywrightDebugServer } = await import('shiplightai/debugger-pw');

  const server = await startPlaywrightDebugServer({
    yamlFilePath: ${JSON.stringify(yamlFilePath)},
    port: ${internalPort},
    page,
    agent,
    testContext,
    projectRoot: ${JSON.stringify(projectRoot ?? null)},
  });

  console.error('[debugger] Playwright sandbox ready on internal port ${internalPort}');

  // Keep alive until the server is closed externally (Ctrl+C kills the process)
  await new Promise(() => {});
});
`;
}

/**
 * Find an available port for the internal Playwright sandbox server.
 */
async function findAvailablePort(startPort: number): Promise<number> {
  const { createServer } = await import("net");
  for (let port = startPort; port < startPort + 20; port++) {
    const available = await new Promise<boolean>((resolve) => {
      const s = createServer();
      s.once("error", () => resolve(false));
      s.once("listening", () => {
        s.close(() => resolve(true));
      });
      s.listen(port, "127.0.0.1");
    });
    if (available) return port;
  }
  throw new Error(`No available port found in range ${startPort}-${startPort + 19}`);
}

/**
 * Spawn the Playwright test process and return a proxy sandbox.
 * The Playwright process starts an internal HTTP server that the proxy talks to.
 */
export async function spawnPlaywrightProcess(options: {
  yamlFilePath: string;
  configPath: string;
  /**
   * Optional unique suffix for the generated .spec.ts file. Required when
   * spawning multiple concurrent debugger sessions in the same directory
   * (e.g. the testbox's multi-session manager) so the temp filenames don't
   * collide. Defaults to empty (current CLI single-session behavior).
   */
  tempSuffix?: string;
  /**
   * When true, append `--headed` to the Playwright invocation. The debugger
   * SPA already exposes a live CDP view of the browser in its right-side
   * pane (both for CLI and testbox), so a separate headed window is
   * redundant and steals focus on every simulated input. Pass true only
   * when the consumer explicitly wants a second physical window. Note:
   * `--headed` overrides `use.headless` in the user's playwright.config.ts.
   */
  headed: boolean;
}): Promise<{
  port: number;
  /**
   * The loopback address the inner's Express actually bound to. Older
   * shiplightai versions bind "localhost" (IPv6 first on macOS); current
   * source binds 127.0.0.1. We discover which family is reachable during
   * the poll loop and return it so the outer proxy uses the right host.
   */
  host: string;
  pid: number;
  cleanup: () => Promise<void>;
}> {
  const { yamlFilePath, configPath, tempSuffix = "", headed } = options;
  const configDir = path.dirname(configPath);

  // Only the internal sandbox HTTP server needs a pre-allocated port (we can't
  // let it float — the outer proxy has to know where to forward). Chromium's
  // CDP port is negotiated dynamically inside the inner: Chromium launches
  // with --remote-debugging-port=0, writes the chosen port + ws path into
  // <its-user-data-dir>/DevToolsActivePort, and the inner reads that file.
  const internalPort = await findAvailablePort(16174);

  // Extract the `use` block from the YAML — see resolveDebugUseBlock for how
  // `base_url` (either spelling) folds into `baseURL` and takes precedence
  // over an explicit `use.baseURL`.
  let use: Record<string, unknown> | undefined;
  if (!fs.existsSync(yamlFilePath)) {
    throw new Error(`Please select a test file before starting the debug session. File not found: ${yamlFilePath}`);
  }
  try {
    use = resolveDebugUseBlock(parseYaml(fs.readFileSync(yamlFilePath, "utf-8")));
  } catch (err) {
    console.error("[debugger] Could not parse YAML for `use` block:", err);
  }

  const tmpTestDir = path.dirname(path.resolve(yamlFilePath));
  const suffix = tempSuffix ? `-${tempSuffix}` : "";
  const tmpTestPath = path.join(tmpTestDir, `.__shiplight_debug__${suffix}.yaml.spec.ts`);
  const testContent = generateDebugTestCode(yamlFilePath, internalPort, use, configDir);
  fs.writeFileSync(tmpTestPath, testContent);

  // Clean up temp spec file. Called from every exit path. (Chromium's own
  // user-data-dir is created and cleaned up by Playwright.) See
  // makeIdempotentFileCleaner for the rationale and a covering test.
  const cleanupTempArtifacts = makeIdempotentFileCleaner(tmpTestPath);

  // Build playwright args — use a path relative to configDir (the cwd of the
  // child process) so the arg contains no drive letter or absolute separators.
  // On Windows, an absolute path like C:\Users\...\file.ts passed as a
  // Playwright filter causes two problems: backslashes are regex escape chars,
  // and "C:" contains a colon that may confuse path/regex matching. A relative
  // path sidesteps both: in the common case (yaml alongside the config) it
  // reduces to just the filename with no separators at all. Normalize remaining
  // backslashes to forward slashes for the subdirectory case.
  const relTestPath = path.relative(configDir, tmpTestPath).replace(/\\/g, "/");
  const pwArgs = ["playwright", "test", relTestPath, ...(headed ? ["--headed"] : [])];

  const child = spawn("npx", pwArgs, {
    stdio: ["ignore", "pipe", "pipe"],
    shell: true,
    cwd: configDir,
    // The debugger has its own embedded browser view (the debugger SPA hosts
    // a CDP live-view in its iframe), so it doesn't need — and shouldn't —
    // register its Chromium with the testbox's browser registry. Clearing
    // OMNITERM_BROWSER_REGISTRY_URL here makes `registerBrowser()` a no-op for the
    // whole subtree: the fixture's registration hook AND any nested `sdk-core`
    // agent calls skip the registry. The debugger's view continues to work
    // because it's wired through the DebuggerManager's own /ws/debugger/...
    // proxy, not the registry.
    env: { ...process.env, PWDEBUG: "console", OMNITERM_BROWSER_REGISTRY_URL: "" },
  });

  // Pipe child output to parent stderr (shows in VS Code output channel)
  child.stdout?.on("data", (chunk: Buffer) => {
    process.stderr.write(chunk);
  });
  child.stderr?.on("data", (chunk: Buffer) => {
    process.stderr.write(chunk);
  });

  // Forward termination signals
  const killChild = () => {
    if (!child.killed) child.kill("SIGTERM");
  };
  process.on("SIGTERM", killChild);
  process.on("SIGINT", killChild);
  process.on("exit", killChild);

  // Handle child exit
  child.on("close", (code) => {
    process.removeListener("SIGTERM", killChild);
    process.removeListener("SIGINT", killChild);
    process.removeListener("exit", killChild);
    // Clean up temp file
    cleanupTempArtifacts();
    if (code !== 0 && code !== null) {
      console.error(`[debugger] Playwright process exited with code ${code}`);
    }
  });

  // Wait for the internal sandbox server to be ready.
  // Probe both loopback families — older shiplightai binds "localhost"
  // (IPv6 on macOS); current source binds 127.0.0.1. Whichever answers
  // first is what we'll use for all subsequent outer→inner traffic.
  //
  // We store the BARE host (`::1`, not `[::1]`) so it can be passed
  // directly to `http.request({ hostname })`, which rejects bracketed
  // forms. Callers building URL strings must wrap IPv6 hosts in brackets
  // themselves.
  console.error("[debugger] Waiting for Playwright sandbox to start...");
  const candidateHosts = ["127.0.0.1", "::1"] as const;
  async function probeHost(host: string): Promise<boolean> {
    try {
      const urlHost = host.includes(":") ? `[${host}]` : host;
      const res = await fetch(`http://${urlHost}:${internalPort}/api/test-flow`);
      if (res.ok) {
        try { await res.text(); } catch {}
        return true;
      }
    } catch {
      // Not ready on this family yet
    }
    return false;
  }
  let resolvedHost: string | null = null;
  for (let i = 0; i < 180; i++) {
    if (child.exitCode !== null) {
      cleanupTempArtifacts();
      throw new Error(`Playwright process exited with code ${child.exitCode} before sandbox was ready`);
    }
    for (const h of candidateHosts) {
      if (await probeHost(h)) {
        resolvedHost = h;
        break;
      }
    }
    if (resolvedHost) {
      console.error(`[debugger] Playwright sandbox ready on ${resolvedHost}:${internalPort}`);
      break;
    }
    if (i === 179) {
      killChild();
      cleanupTempArtifacts();
      throw new Error("Timed out waiting for Playwright sandbox to start (180s)");
    }
    await new Promise((r) => setTimeout(r, 1000));
  }

  if (!resolvedHost) {
    killChild();
    cleanupTempArtifacts();
    throw new Error("Sandbox poll finished without a reachable host");
  }

  return {
    port: internalPort,
    host: resolvedHost,
    pid: child.pid ?? 0,
    cleanup: async () => {
      killChild();
      cleanupTempArtifacts();
    },
  };
}
