/**
 * Transpile Engine
 *
 * Scans for *.test.yaml files and generates *.yaml.spec.ts next to each,
 * with mtime-based caching (including referenced template files).
 */

import { readFileSync, statSync, existsSync } from 'fs';
import { resolve, relative } from 'path';
import { globSync } from 'glob';
import { transpileYamlContent, parseYamlTestFile } from './yaml-transpiler';
import type { ActionEntityStore } from 'shiplight-types';
import { fingerprintActionEntity } from 'shiplight-types';
import { mergeInlineFingerprintMap } from './cache/inlineFingerprintMap.js';
import {
  markRunCacheInPlay,
  markRunMeasurementIncomplete,
  resetRunCacheMetadata,
  runCacheCollector,
} from './cache/runCacheMetadata.js';
import { TRANSPILER_CACHE_KEY } from './transpiler/version';

/**
 * Get file mtime in milliseconds, or 0 if the file doesn't exist.
 */
function getMtimeMs(filePath: string): number {
  try {
    return statSync(filePath).mtimeMs;
  } catch {
    return 0;
  }
}

const VERSION_HEADER = `// @generated by shiplightai v${TRANSPILER_CACHE_KEY}`;

/**
 * Check if the generated output file is up-to-date relative to
 * the YAML source, all referenced template files, and the transpiler version.
 */
function isUpToDate(outPath: string, sourcePaths: string[]): boolean {
  if (!existsSync(outPath)) return false;

  // Check version header matches current transpiler
  const firstLine = readFileSync(outPath, 'utf-8').split('\n', 1)[0];
  if (firstLine !== VERSION_HEADER) return false;

  const outMtime = getMtimeMs(outPath);
  for (const src of sourcePaths) {
    if (getMtimeMs(src) > outMtime) return false;
  }
  return true;
}

/**
 * Extract YAML test files targeted by process.argv.
 * Playwright passes test file paths as bare args (e.g. `npx playwright test tests/foo.test.yaml`).
 * Returns matching .test.yaml relative paths, or null if no specific files were requested.
 *
 * `argv` defaults to `process.argv.slice(2)` (the transpiler runs inside the spawned
 * Playwright process, where that is Playwright's argv). The CLI orchestrator passes its
 * own resolved args explicitly so the pre-test cache download scopes to the SAME files
 * this run will transpile — see `preTestDownload` in commands/test.ts.
 */
export function getRequestedYamlFiles(cwd: string, args: string[] = process.argv.slice(2)): string[] | null {
  const files: string[] = [];

  const resolvedCwd = resolve(cwd);

  for (const arg of args) {
    if (arg.startsWith('-')) continue;
    // Accept both .test.yaml and .yaml.spec.ts references
    const yamlFile = arg.endsWith('.yaml.spec.ts')
      ? arg.replace(/\.yaml\.spec\.ts$/, '.test.yaml')
      : arg;
    if (!yamlFile.endsWith('.test.yaml')) continue;
    // Resolve relative to cwd and back to get a consistent relative path
    const abs = resolve(cwd, yamlFile);
    if (existsSync(abs)) {
      files.push(abs.startsWith(resolvedCwd) ? abs.slice(resolvedCwd.length + 1) : yamlFile);
    }
  }

  return files.length > 0 ? files : null;
}

/**
 * Transpile *.test.yaml files found under the given directory.
 * If Playwright was invoked with specific test files, only those are transpiled.
 * Otherwise all *.test.yaml files are transpiled.
 *
 * @param options.cwd - Directory to scan for .test.yaml files
 * @param options.actionEntityStores - Optional map of relative file path → ActionEntityStore
 *   (populated by the CLI orchestrator from cloud cache or local files)
 */
export function transpileAllYamlTests(options: {
  cwd: string;
  /** Project root for resolving template paths that aren't found relative to the test file. Defaults to cwd. */
  projectRoot?: string;
  actionEntityStores?: Map<string, ActionEntityStore>;
}): void {
  const requested = getRequestedYamlFiles(options.cwd);
  const yamlFiles = requested ?? globSync('**/*.test.yaml', {
    cwd: options.cwd,
    ignore: ['**/node_modules/**'],
  });

  const errors: Array<{ file: string; error: unknown }> = [];
  const inlineFingerprints: Record<string, string> = {};

  // This function runs exactly once per test run (from shiplightConfig), so it
  // is the only place that can clear state left by a previous run in the same
  // process — Playwright's watch/UI mode re-evaluates the config in place.
  resetRunCacheMetadata();

  // Whether this run has an action-entity cache at all. Two consequences:
  // the cache summary is only reported for runs where the feature is active,
  // and — see the skip below — such a run must transpile EVERY file so the
  // summary covers the whole run rather than whichever files happened to be
  // stale.
  const measuring = options.actionEntityStores !== undefined;
  if (measuring) markRunCacheInPlay();

  for (const file of yamlFiles) {
    const yamlPath = resolve(options.cwd, file);
    const outPath = yamlPath.replace(/\.test\.yaml$/, '.yaml.spec.ts');

    const yaml = readFileSync(yamlPath, 'utf-8');

    try {
      // Parse to get referenced template paths for cache invalidation
      const parsed = parseYamlTestFile(yaml, yamlPath, options.projectRoot ?? options.cwd);
      // Look up cached action entities for this file (if provided by orchestrator)
      const relPath = relative(options.cwd, yamlPath);
      const actionEntityStore = options.actionEntityStores?.get(relPath)
        ?? options.actionEntityStores?.get('*');  // wildcard: merged store for all files
      const hasCache = actionEntityStore && Object.keys(actionEntityStore.entries).length > 0;

      // Skip re-transpilation if up-to-date AND nothing needs observing.
      // `measuring` deliberately defeats the mtime cache: the summary is built
      // only from what the transpiler sees, so skipping even one file would
      // publish a hit rate measured over an arbitrary subset of the run (the
      // stale files) and present it as the whole. The expensive half —
      // parseYamlTestFile, above — already ran either way; only codegen and the
      // write are given up.
      //
      // Side effect to be aware of: every `.yaml.spec.ts` is rewritten on every
      // run once a cache is present, so their mtimes churn. That is safe only
      // because the emitted spec is byte-identical for unchanged YAML — which
      // is exactly why hook and suite statements must carry deterministic UIDs
      // (see assignDeterministicUids). It matters beyond tidiness: Playwright
      // re-imports playwright.config.ts in EVERY worker process, so this rewrite
      // also happens per worker, mid-run. If a rewrite were not a no-op, workers
      // would execute a spec that no longer matched what the main process
      // recorded. Watch-mode tooling observing the workspace will see the
      // touches.
      if (!hasCache && !measuring && isUpToDate(outPath, [yamlPath, ...parsed.referencedTemplatePaths])) continue;

      // Buffered, not written straight through to the collector: the generated
      // spec is syntax-checked and written AFTER every action is walked, so a
      // file that fails to transpile would otherwise contribute statements to
      // the summary while the previous run's stale spec — built without this
      // cache — is what Playwright actually executes.
      const observed: Array<Parameters<ReturnType<typeof runCacheCollector>['recordStatementSource']>> = [];

      // Pass the pre-parsed result to avoid re-parsing (which would generate new UIDs
      // that don't match the store keys built from the first parse)
      const result = transpileYamlContent(yaml, yamlPath, {
        version: TRANSPILER_CACHE_KEY,
        actionEntityStore,
        parsed,
        projectRoot: options.projectRoot ?? options.cwd,
        // Transpilation is the only point that knows whether each action came
        // from the cache or from the YAML; the reporter folds in healing later
        // and emits the summary. Records are keyed by statement UID.
        onActionEntitySource: (info) =>
          observed.push([
            info.uid,
            relPath,
            info.description,
            info.source,
            info.originalEntity,
            info.cachedEntity,
          ]),
      });

      if (!result.valid) {
        throw new Error(result.errors.join('; '));
      }

      const collector = runCacheCollector();
      for (const record of observed) collector.recordStatementSource(...record);
      for (const [uid, , , , originalEntity] of observed) {
        inlineFingerprints[uid] = fingerprintActionEntity(originalEntity);
      }
    } catch (err) {
      console.error(`[shiplight] Failed to transpile ${file}:`, err);
      errors.push({ file, error: err });
      // This file's statements went unobserved, and the spec Playwright will run
      // for it is whatever a previous transpile left behind. Any summary built
      // from the rest of the run would be measured over an unknown fraction of it.
      markRunMeasurementIncomplete();
    }
  }

  // Handed to the post-run cache write-back, which runs in the parent process and
  // cannot see inline entities. Written before the error check below so a run that
  // partially failed to transpile still stamps the files that did transpile.
  //
  // Anchored to projectRoot, NOT cwd. `shiplightConfig` passes `cwd: scanDir`, which an
  // explicit `scanDir` option narrows to a subfolder, while the write-back reads from
  // projectRoot — so anchoring this to cwd would put the map somewhere the reader never
  // looks and leave every entry unstamped (and therefore grandfathered) for exactly the
  // projects that configure one. They coincide whenever scanDir is not set.
  mergeInlineFingerprintMap(options.projectRoot ?? options.cwd, inlineFingerprints);

  if (errors.length > 0) {
    const msg =
      `[shiplight] Transpilation failed for ${errors.length} file(s):\n` +
      errors.map((e) => `  - ${e.file}`).join('\n');

    if (requested) {
      // Fail hard when the user explicitly requested these files
      throw new Error(msg);
    }
    console.warn(msg + ' (skipped)');
  }
}

